### ISSUE TITLE
core: ./core is not exported in package.json

### ISSUE THREAD

**Issue by jeromevdl** [aws/aws-cdk#17950]
### What is the problem?

When migrating to cdk 2.1.0, i have the following error:
> Error: Package subpath './core' is not defined by "exports" in /.../node_modules/aws-cdk-lib/package.json

(and actually, it is not in the package.json)

### Reproduction Steps

In my code:

`import { CfnOutput, SecretValue, Stage, Stack } from 'aws-cdk-lib/core';`

Use **cdk 2.1.0** in package.json:

```
"devDependencies": {
    "aws-cdk": "2.1.0",
  },
  "dependencies": {
    "aws-cdk-lib": "2.1.0",
    "constructs": "10.0.12",
  }
```

Then try to synthesise: 
> cdk synth

Gives the error: 
> Error: Package subpath './core' is not defined by "exports" in /.../node_modules/aws-cdk-lib/package.json

### What did you expect to happen?

I expected to have get the template synthesised. 

### What actually happened?

The following error (line 18 is the import statement above):

> Error: Package subpath './core' is not defined by "exports" in /.../node_modules/aws-cdk-lib/package.json
>     at new NodeError (node:internal/errors:371:5)
>     at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
>     at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
>     at resolveExports (node:internal/modules/cjs/loader:482:36)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/.../bin/mycode.ts:18:1)

### CDK CLI Version

2.1.0

### Node.js Version

v17.0.1

### OS

mac OS BigSur (M1)

### Language

Typescript

### Language Version

TypeScript  4.5.2

### Other information

Manually adding "./core": "./core/index.js" to the node_modules/aws-cdk-lib/package.json solve the issue, but this is not a viable solution.

**Comment by manumaki** [comment]
Same issue here

**Comment by ryparker** [comment]
In CDK v2 all `@aws-cdk/core` exports are now direct exports of `aws-cdk-lib`

The following should work:
`import { CfnOutput, SecretValue, Stage, Stack } from 'aws-cdk-lib';`

**Comment by peterwoodworth** [comment]
Be sure to view https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html for more information on migrating to CDK v2, and the differences between v1 and v2

**Comment by Cristian-Vt** [comment]
anyone found a resolution for this. I get the same error when I use the core to define s3Buckets.

```
// create bucket
  const s3Bucket = new s3.Bucket(this, 's3-bucket', {
    removalPolicy: cdk.RemovalPolicy.DESTROY,
    autoDeleteObjects: true,
  });

  // 👇 invoke lambda every time an object is created in the bucket
  s3Bucket.addEventNotification(
    s3.EventType.OBJECT_CREATED,
    new s3n.LambdaDestination(lambdaFunction),
    // 👇 only invoke lambda if object matches the filter
    // {prefix: 'test/', suffix: '.yaml'},
  );

  new cdk.CfnOutput(this, 'bucketName', {
    value: s3Bucket.bucketName,
  });  
```

`Error: Package subpath './core' is not defined by "exports" in /.../node_modules/aws-cdk-lib/package.json`

**Comment by mrgrain** [comment]
This worked in CDK 2.0 and started falling in 2.1

I'm not sure if that was working by mistake in 2.0 or if it was an accidental breaking change in 2.1

**Comment by JoshuaToth** [comment]
@ryparker 's fix works fine

`aws-cdk-lib/core` -> `aws-cdk-lib`

**Comment by mrgrain** [comment]
@peterwoodworth @ryparker I think what I be looking for would be a note on the v2.1.0 release notes mentioning this change and linking to the migration docs.

**Comment by zxkane** [comment]
Should it be a breaking change when upgrading from v2.0.0?

**Comment by jeromevdl** [comment]
I have a similar problem with python.

Tried with:

```
from aws_cdk import Stack

class MyStack(Stack):
```

Got `ImportError: cannot import name 'Stack' from 'aws_cdk' (unknown location)`

Also tried with:

```
import aws_cdk as core

class MyStack(core.Stack):
```

Got `AttributeError: module 'aws_cdk' has no attribute 'Stack'`

(using python 3.8.9, cdk 2.1.0)

**Comment by MichaelWalker-git** [comment]
```
  const s3Bucket = new s3.Bucket(this, 's3-bucket', {
    removalPolicy: cdk.RemovalPolicy.DESTROY,
    autoDeleteObjects: true,
  });

  s3Bucket.addEventNotification(
    s3.EventType.OBJECT_CREATED,
    new s3n.LambdaDestination(lambdaFunction),
  );

  new cdk.CfnOutput(this, 'bucketName', {
    value: s3Bucket.bucketName,
  });  
```

@Cristian-Vt , you want to do the following:
- replace new s3.Bucket with aws_s3
- replace new cdk.CfnOutput with just CfnOutput
- your import will look like this: 
```
import { Stack, StackProps, aws_s3, CfnOutput } from 'aws-cdk-lib';

```

**Comment by peterwoodworth** [comment]
For anyone wondering - importing with `aws-cdk-lib/core` was not intended to be in `2.0.0`. The change for that was made in this pull request https://github.com/aws/aws-cdk/pull/17707

Plenty of people have described the correct way to import packages in v2 - so I'm going to close the issue

**Comment by shellscape** [comment]
@peterwoodworth ⚠️ harsh criticism incoming

> Be sure to view https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html for more information on migrating to CDK v2, and the differences between v1 and v2

I've been using v1 for the last two years, more recently using it on a microservice architecture with ~50 services and an extensive wrapper lib, and this guide was relatively useless. I had to turn to Google, SO, and Twitter to find answers to questions like the OP. 

The migration guide doesn't even mention that one can import via `aws-cdk-lib/{target}`. e.g. 

```ts
import { Function } from 'aws-cdk-lib/aws-lambda';
```

instead of 

```ts
import { aws_lambda } from 'aws-cdk-lib';
const { Function } = aws_lambda;
// or even more egregiously using a namespace for everything, which I'm deathly allergic to
```

I still can't wrap my head around why the exports are snake_cased while the entirety of the rest of the framework uses camelCase (with the exception of the classes). Who let the python folks dictate TS/JS export names?

Overall the docs around this migration were disappointing at best. The fact that we still cannot search the CDK API Reference is such a massive oversight I'm not sure how a new major version was released without that most basic of DX requirement for a framework so large.

**Comment by peterwoodworth** [comment]
@shellscape I'm curious what all the issues you had with the migration were, if you had any issues further than what you've described here. Would you be able to open a new issue detailing your issues with the migration guide? Would be more helpful to track a new issue specifically for improving the migration guide imo 🙂

**Comment by shishkin** [comment]
I think the [suggested solution](https://github.com/aws/aws-cdk/issues/17950#issuecomment-991189490) to use the default export is not satisfactory. I'm running into issues when bundlers scan dependencies and choke on things inside the `aws-cdk-lib` that I don't even use (e.g. Dockerfile from `aws-cdk-lib/lambda-layer-kubectl/layer/Dockerfile` 🤷‍♂️ ), but they're still reachable from the bundler's perspective because my code imports `aws-cdk-lib` default export which exports *everything*.

Exporting `core` explicitly would allow for better tree shaking in bundlers. Otherwise `aws-cdk-lib` objectively still remains a monolithic CJS package and neglects benefits of ESM.
