### PR TITLE
fix(core): Record DependableTrait directly on instance

### LINKED ISSUE #2713: External libraries in v0.33.0 throwing `${instance} does not implement DependableTrait`
**Describe the bug**
I've got a few import helper functions I'm pulling in from a cdk library and getting some unexpected behavior trying to make it work on v0.33. If I move the functions into the same lib/stack.ts file they're being called from it works as expected.

From debugging, this error is thrown after the stack is processed.

**To Reproduce**

**app lib/stack.ts**
```
import cdk = require('@aws-cdk/cdk');
import ecs = require('@aws-cdk/aws-ecs');
import ecsL3 = require('@aws-cdk/aws-ecs-patterns')
import ec2 = require('@aws-cdk/aws-ec2');
import cdkLib = require('@cdkLib/cdk');

export class CdkEcsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cluster = cdkLib.clusterImport(this, 'Cluster');

    const service = new ecsL3.LoadBalancedEc2Service(this, 'Service', {
      cluster: cluster,
      memoryLimitMiB: 1024,
      image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      desiredCount: 2,
    });
  }
}
```

**library lib/context-providers/vpcs.ts**
```
import cdk = require('@aws-cdk/cdk');
import ec2 = require('@aws-cdk/aws-ec2');

const Account_1_US_EAST_1 = {
  vpcId: 'vpc-12345',
  availabilityZones: ['us-east-1a', 'us-east-1b'],
  publicSubnetIds: ['subnet-12345', 'subnet-67890'],
  privateSubnetIds: ['subnet-12345', 'subnet-67890']
}
export function vpcImport(scope: cdk.Construct, name: string) {
  const account = scope.node.stack.env.account;
  const region = scope.node.stack.env.region;

  if (account == '1234567890' && region == 'us-east-1') {
    return ec2.Vpc.fromVpcAttributes(scope, name, Account_1_US_EAST_1);
    } else {
    throw new Error(`VPC not found in account ${account}, region ${region}`)
  }
}
```

**library lib/context-providers/ecs.ts**
```
import cdk = require('@aws-cdk/cdk');
import ecs = require('@aws-cdk/aws-ecs');
import ec2 = require('@aws-cdk/aws-ec2');
import { vpcImport } from './vpcs';

export function clusterImport(scope: cdk.Construct, name: string) {
  const account = scope.node.stack.env.account;
  const region = scope.node.stack.env.region;
  const vpc = vpcImport(scope, 'Vpc');

  if (account == '1234567890' && region == 'us-east-1') {
    return ecs.Cluster.fromClusterAttributes(scope, name, {
      clusterName: 'name',
      securityGroups: [ec2.SecurityGroup.fromSecurityGroupId(scope, 'ecs', 'sg-123456')],
      vpc: vpc
    });
  } else {
    throw new Error(`Cluster not found in account ${account}, region ${region}`);
  }
}
```

`cdk ls or diff`

**Expected behavior**
The external functions should resolve like normal and allow the stack to be built and diff/ls commands to work. 

**Version:**
 - MacOS 10.14.5
 - TS 3.3.333 ts-node 8.2.0 Node 12.3.1
 - CDK Version 0.33.0

### PR DESCRIPTION
**Pull request by RomainMuller**
The use of the WeakMap caused difficulties for construct library authors, because they
could occasionally operate on a different instance of the @aws-cdk/cdk library.

Fixes #2713

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by orangewise** [comment]
Awesome, thanks!
