### ISSUE TITLE
Missing exports in @aws-cdk/aws-lambda-event-sources v1.11.0

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#4358]
It's impossible to use the DynamoDB or Kinesis event source from `@aws-cdk/aws-lambda-event-sources` in v1.11.0 because there are missing exports in `stream.d.ts`: https://unpkg.com/browse/@aws-cdk/aws-lambda-event-sources@1.11.0/lib/stream.d.ts

### Reproduction Steps

Use `@aws-cdk/aws-lambda-event-sources` in your app.

### Error Log

`error TS2305: Module '"./stream"' has no exported member 'StreamEventSource'.`
`error TS2305: Module '"./stream"' has no exported member 'StreamEventSourceProps'.`

### Environment

  - **CLI Version      :** 1.11.0
  - **Framework Version:** 1.11.0
  - **OS               :** all
  - **Language         :** all

### Other

This has been introduced in #4260 (4040032) and is most probably linked to the `@internal` https://github.com/aws/aws-cdk/blob/4040032a7944bf60dee4bf07d3d73a70874270e0/packages/%40aws-cdk/aws-lambda-event-sources/lib/stream.ts#L5?

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Duplicate of #4352

**Comment by jogold** [comment]
> Duplicate of #4352

Exactly, missed it.
