### ISSUE TITLE
(aws-eks): "abstract async" should not be used

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#12881]
The EKS library (at `lib/cluster-resource-handler/common.ts`) declares a few `protected abstract async` methods, which was unintentionally accepted by the TypeScript compiler, but is no longer accepted by TypeScript >= 4.1.

These should be fixed. The below diagnostics are produced with an experimental version of `jsii` that builds with TypeScript 4.1.3:

```
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:67:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 67   protected abstract async onCreate(): Promise<OnEventResponse>;
@aws-cdk/aws-eks:                         ~~~~~
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:68:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 68   protected abstract async onDelete(): Promise<OnEventResponse | void>;
@aws-cdk/aws-eks:                         ~~~~~
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:69:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 69   protected abstract async onUpdate(): Promise<(OnEventResponse & EksUpdateId) | void>;
@aws-cdk/aws-eks:                         ~~~~~
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:70:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 70   protected abstract async isCreateComplete(): Promise<IsCompleteResponse>;
@aws-cdk/aws-eks:                         ~~~~~
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:71:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 71   protected abstract async isDeleteComplete(): Promise<IsCompleteResponse>;
@aws-cdk/aws-eks:                         ~~~~~
@aws-cdk/aws-eks: lib/cluster-resource-handler/common.ts:72:22 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
@aws-cdk/aws-eks: 72   protected abstract async isUpdateComplete(): Promise<IsCompleteResponse>;
@aws-cdk/aws-eks:                         ~~~~~
```

---

More information through the reasoning of why `abstract async` was a bad thing: https://github.com/microsoft/TypeScript/issues/28516
