### ISSUE TITLE
Error metric.toMetricConfig is not a function

### ISSUE THREAD

**Issue by toleabivol** [aws/aws-cdk#5829]
Hello,

After updating from 1.18.0 to 1.21.0 I get this error when running cdk synth or cdk deploy: 
jsii.errors.JSIIError: metric.toMetricConfig is not a function.

I can see the function in master branch JS version but not in the python 1.21.0 module version.
https://github.com/aws/aws-cdk/blob/d4c1b0ee84abb1c0ca24ddf1260a4b2161dde7b8/packages/%40aws-cdk/aws-cloudwatch/lib/metric.ts#L286

### Reproduction Steps

scaling = autoscalinggroup.scale_on_metric(
            f'ScaleToNrRenderingMessInQueue-{stage}-{app_name}-{version}',
            metric=queue.metric("ApproximateNumberOfMessagesVisible"),
            scaling_steps=[
                autoscaling.ScalingInterval(upper=0, change=0),
                autoscaling.ScalingInterval(lower=0, upper=1, change=1),
                autoscaling.ScalingInterval(lower=2, upper=3, change=2),
                autoscaling.ScalingInterval(lower=3, change=3)
            ],
            adjustment_type=autoscaling.AdjustmentType.EXACT_CAPACITY,
            estimated_instance_warmup=core.Duration.seconds(300),
            cooldown=core.Duration.seconds(300)
        )

### Error Log

jsii.errors.JSIIError: metric.toMetricConfig is not a function

### Environment

  - **CDK CLI Version:** 1.21.0 (build bf6ab14)
  - **Module Version:** 1.21.0
  - **OS:** Windows 7
  - **Language:** Python

### Other

(venvname)  C:\Users\abivol\repos\venvname\cdk>cdk synth
897281259418
eu-west-1
jsii.errors.JavaScriptError:
  TypeError: metric.toMetricConfig is not a function
      at aggregationTypeFromMetric (C:\Users\abivol\AppData\Local\Temp\jsii-kernel-etQTxE\node_modules\@aws-cdk\aws-autoscaling\lib\step-scaling-policy.js:83:36)
      at new StepScalingPolicy (C:\Users\abivol\AppData\Local\Temp\jsii-kernel-etQTxE\node_modules\@aws-cdk\aws-autoscaling\lib\step-scaling-policy.js:29:40)
      at AutoScalingGroup.scaleOnMetric (C:\Users\abivol\AppData\Local\Temp\jsii-kernel-etQTxE\node_modules\@aws-cdk\aws-autoscaling\lib\auto-scaling-group.js:104:16)
      at C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7589:51
      at Kernel._wrapSandboxCode (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:8225:19)
      at C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7589:25
      at Kernel._ensureSync (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:8198:20)
      at Kernel.invoke (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7588:26)
      at KernelHost.processRequest (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7296:28)
      at KernelHost.run (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7236:14)
      at Immediate._onImmediate (C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7239:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 34, in <module>
    region=AWS_REGION
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\abivol\repos\venvname\cdk\digital_brochure_stack.py", line 372, in __init__
    estimated_instance_warmup=core.Duration.seconds(300)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\aws_cdk\aws_autoscaling\__init__.py", line 5423, in scale_on_metric
    return jsii.invoke(self, "scaleOnMetric", [id, props])
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_kernel\__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_kernel\__init__.py", line 288, in invoke
    args=_make_reference_for_native(self, args),
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_kernel\providers\process.py", line 348, in invoke
    return self._process.send(request, InvokeResponse)
  File "C:\Users\abivol\.virtualenvs\venvname-k8Lrhq7m\lib\site-packages\jsii\_kernel\providers\process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: metric.toMetricConfig is not a function
Subprocess exited with error 1

--- 

This is :bug: Bug Report
