### ISSUE TITLE
(pipelines): CdkStage not exported at 2.0.0-rc.25

### ISSUE THREAD

**Issue by Hi-Fi** [aws/aws-cdk#17152]
### What is the problem?

When updating aws-cdk-lib to 2.0.0-rc.25, compilation starts to fail with following error:
```
src/LegacyStage.ts:30:33 - error TS2694: Namespace '"/workspace/cdk-test-stage/node_modules/aws-cdk-lib/lib/pipelines/index"' has no exported member 'CdkStage'.
``` 

### Reproduction Steps

```
import {
  pipelines,
} from 'aws-cdk-lib';
const cdkStage: pipelines.CdkStage = undefined;
```

### What did you expect to happen?

IDE finds out exported member.

### What actually happened?

Error:
```
Namespace '"/workspace/cdk-test-stage/node_modules/aws-cdk-lib/lib/pipelines/index"' has no exported member 'CdkStage'.ts(2694)
```

### CDK CLI Version

2.0.0-rc.25

### Node.js Version

v14.17.6

### OS

Linux 073f04487f9e 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

### Language

Typescript

### Language Version

TypeScript (4.4.3)

**Comment by skinny85** [comment]
Hey @Hi-Fi,

apologies, this issue somehow slipped through the cracks 😕.

Were you able to figure this out? Does this problem still happen with a stable version of `aws-cdk-lib` (`2.0.0` and later)?

Thanks, and apologies again,
Adam

**Comment by Hi-Fi** [comment]
We dropped support for legacy pipelines (CDKPipelines), so haven't checked it, but I think it was removed on purpose from v2. 

At the time of the issue it was just a bit unclear how it will be, as export was just gone.

**Comment by skinny85** [comment]
OK. I guess we can close this one then? Please comment if you need anything else from our side.
