### PR TITLE
fix(awslint): use a default import for chalk

### LINKED ISSUE #38109: (awslint): namespace import of chalk breaks under esModuleInterop — all lint diagnostics are silently swallowed and builds fail with no output
### Describe the bug

`packages/awslint` is broken on `main`: every lint diagnostic it produces is silently discarded, and when there are error-level findings the build fails at the `cdk-awslint` step with **no output at all**, making the failure undiagnosable.

Root cause: `chalk.red`, `chalk.cyan`, `chalk.bold`, etc. are all `undefined` at runtime, so awslint's result printer never prints and its top-level error handler throws.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

Introduced by #38058 ("chore: prepare repo for TypeScript/JSII 6.0"), which changed `packages/awslint/tsconfig.json` from `"module": "commonjs"` (no `esModuleInterop`) to `"module": "Node20"` **and added `"esModuleInterop": true`**.

### Expected Behavior

`awslint` prints its diagnostics (errors/warnings), and on failure emits a clear message naming the offending rule and scope (e.g. `error: [awslint:docs-public-apis:aws-cdk-lib.pipelines.Step] ...`).

### Current Behavior

- `cd packages/awslint && node bin/awslint.js list` crashes:
  ```
  TypeError: chalk.red is not a function
      at .../packages/awslint/bin/awslint.js:234
  ```
- During a normal build of `packages/aws-cdk-lib`, any awslint **error** makes the build fail with only:
  ```
  Error: .../tools/@aws-cdk/cdk-build-tools/bin/cdk-awslint exited with error code 1
  Build failed.
  ```
  and **zero** diagnostic output. In the results loop the print is gated on `if (color)`, where `color = chalk.red` is `undefined`, so nothing is ever printed — yet `errors++` still runs and sets `process.exitCode = 1`. Warnings are likewise swallowed.

### Reproduction Steps

1. Fresh checkout of `main`, `yarn install`.
2. `cd packages/awslint && npx tsc -b --force`
3. `node bin/awslint.js list` → `TypeError: chalk.red is not a function`.

Root-cause demonstration (mirrors what the compiler emits for `import * as chalk from 'chalk'`):
```js
function importStar(m){var r={};if(m!=null)for(var k in m)if(k!=='default'&&Object.prototype.hasOwnProperty.call(m,k))r[k]=m[k];r.default=m;return r;}
const chalk = importStar(require('chalk'));
typeof require('chalk').red    // 'function'
typeof chalk.red               // 'undefined'   <-- the bug
typeof chalk.default.red       // 'function'    <-- color fns are only on .default
```

### Possible Solution

`bin/awslint.ts` does `import * as chalk from 'chalk'` and accesses `chalk.red`/`chalk.cyan`/`chalk.bold` as namespace members. Under the `esModuleInterop: true` + `module: "Node20"` introduced by #38058 this compiles to `__importStar(require("chalk"))`, and chalk v4 (CJS, default-export function) exposes its color methods only on the wrapper's `.default`, so the namespace members are `undefined`.

Minimal fix: use a default import —
```ts
import chalk from 'chalk';
```
(or upgrade chalk to v5 and use named/default imports). Separately, the top-level `main().catch(e => console.error(chalk.red(e.message)))` should not itself depend on `chalk.red`, so that errors are never silently lost.

### Additional Information/Context

Affects all contributors — any awslint rule violation now fails the build with no actionable message. Discovered when a `docs-public-apis` violation produced a completely silent build failure.

### AWS CDK Library version (aws-cdk-lib)

N/A — internal build tooling (`packages/awslint`), reproduced on `main` @ `35b4d3bb27`.

### AWS CDK CLI version

N/A

### Node.js Version

v24.14.0

### OS

macOS (darwin)

### Language

TypeScript

### Language Version

TypeScript 5.9.3

### Other information

`packages/awslint` declares `chalk: ^4` (installed: 4.1.2). The bug is independent of the chalk patch version; it is the `import * as chalk` + `esModuleInterop` interaction.

### PR DESCRIPTION
**Pull request by laazyj**
### Issue # (if applicable)

Closes #38109.

### Reason for this change

`packages/awslint` is broken on `main`: `awslint list` crashes with `TypeError: chalk.red is not a function`, and during a normal build every awslint diagnostic is **silently swallowed** while the build still fails at the `cdk-awslint` step with **no output**, making failures undiagnosable.

`bin/awslint.ts` imports chalk as a namespace (`import * as chalk from 'chalk'`) and uses `chalk.red` / `chalk.cyan` / `chalk.bold` as namespace members. Since #38058 set `esModuleInterop: true` and `module: "Node20"` on the awslint tsconfig, this now compiles to `__importStar(require("chalk"))`. chalk v4 is a CommonJS default-export function, so its color methods end up only on the wrapper's `.default` — every `chalk.<color>` is `undefined` at runtime. In the results loop the print is gated on `if (color)` where `color = chalk.red` is `undefined`, so nothing prints, yet `errors++` still sets a non-zero exit code.

### Description of changes

Switch the namespace import to a default import:

```diff
-import * as chalk from 'chalk';
+import chalk from 'chalk';
```

This compiles to `chalk.default.<color>` and restores the color functions. One line; no behavioural change beyond making chalk work again.

### Description of how you validated your changes

Rebuilt `packages/awslint` (`tsc -b && eslint && pkglint`, clean) and ran the deterministic repro:

- **Before:** `node bin/awslint.js list` → `TypeError: chalk.red is not a function` (exit 1).
- **After:** `node bin/awslint.js list` → prints all 47 rules in colour (exit 0); `awslint` over `aws-cdk-lib` runs clean and now surfaces diagnostics through the same `chalk.default.*` path.

### Checklist

- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by laazyj** [comment]
**Exemption Request**: This fixes the `packages/awslint` build tool itself (a one-line `chalk` import change); no integration test is applicable. Validated by rebuilding awslint and the deterministic `awslint list` before/after repro described in the PR body. Requesting `pr-linter/exempt-integ-test`.

**Review by matboros — DISMISSED** [review]

**Review by matboros — APPROVED** [review]
