### ISSUE TITLE
CloudWatch Events: rule constructor type error

### ISSUE THREAD

**Issue by markcarroll** [aws/aws-cdk#5463]
Since updating to 1.19 I get an error from the Events.Rule constructor and Events.Schedule.Rate method.
Both seem to imply they are referencing a different version of cdk core. 

### Reproduction Steps

```typescript
    new events.Rule(this, "Traffic-Incidents-Schedule", {
      description: ``,
      enabled: true,
      schedule: events.Schedule.rate(cdk.Duration.minutes(1)),
      targets: [new targets.LambdaFunction(myFunction)],
    });
```

### Error Log

```
lib/myStack.ts:129:21 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'MyStack' is not assignable to type 'Construct'.
    Types of property 'node' are incompatible.
      Type 'import("/project/node_modules/@aws-cdk/core/lib/construct").ConstructNode' is not assignable to type 'import("/project/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/core/lib/construct").ConstructNode'.
        Types have separate declarations of a private property 'host'.
``` 

```
lib/myStack.ts:132:38 - error TS2345: Argument of type 'import("/project/node_modules/@aws-cdk/core/lib/duration").Duration' is not assignable to parameter of type 'import("/project/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/core/lib/duration").Duration'.
  Types have separate declarations of a private property 'amount'.
```

### Environment

  - **CLI Version      :1.19
  - **Framework Version:1.19
  - **OS               :  macOS Catalina
  - **Language         : Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Please show me your `package.json` (are all libraries the same version?) and be sure to have run `npm install`.

**Comment by markcarroll** [comment]
well I restored package.json from previous commit, did the upgrade again and this time it worked so I'll close this. Sorry for the false alarm. Maybe one of the files in npm updated later than the others.
