### PR TITLE
release: v1.16.3

### LINKED ISSUE #1845: CDK for .NET does not use the compiler to flag construct required properties
I am using the CDK version 0.24.1 with c#. If I create a stack that contains this:

```csharp
new Amazon.CDK.AWS.Lambda.Function(this, "SomeId", new FunctionProps());
```
It compiles perfectly. But then, when I run `cdk diff`, I get the following error:
```
Unhandled Exception: Amazon.JSII.Runtime.JsiiException: Cannot read property 'name' of undefined
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
```
So two problems here:
1. The error message does not say anything useful. It is pretty hard to know which construct is causing the error.
2. The error is caused by the fact that I didn't provide the **required** `FunctionProps` properties to my lambda. The required function properties are `handler`, `code` and `runtime`.

I'd like to focus on the second point. The fact that we get a **runtime** error and not a **compile** time error is a big lost compared to TypeScript. In TypeScript, if I don't provide a required property, I see it directly in my IDE:

image

Given that C# is a compiled language, I would expect that all required properties be enforced at compile time. 

In my opinion, the way to do this is simply to use constructor for the different `props`. For example, the `FunctionProps` is currently defined like this:

```csharp
public class FunctionProps : DeputyBase, IFunctionProps
{
   // The class just has a default/empty constructor
   public FunctionProps() {}
   // These 3 properties are required but there is no way to differentiate 
   // them from optional properties from the compiler point of view.
   public string Handler { get; set; }
   public Code Code { get; set; }
   public Runtime Runtime { get; set; }
   // All other properties are optional
   public string FunctionName { get; set; }
}
```
My suggestion would be to use a constructor with parameters instead of relying on getters/setters. Ex:
```csharp
public class FunctionProps : DeputyBase, IFunctionProps
{
    public FunctionProps(
        // Required parameters come first and don't have default values.
        string handler,
        Code code,
        Runtime runtime,
        // Optional parameters come second and *DO* have default values
        string functionName = null)
    {
        Handler = handler;
        Code = code;
        Runtime = runtime;
        FunctionName = functionName;
    }

    // Required properties
    public string Handler { get; set; }
    public Code Code { get; set; }
    public Runtime Runtime { get; set; }
    // Optional properties
    public string FunctionName { get; set; }
}
```
With such code, I get a nice intellisense that tells me what is required and what is optional:

image

And if I instantiate a `FunctionProps` and don't provide the required properties, I get a compile time error:
```
error CS7036: There is no argument given that corresponds to the required formal parameter 'handler' of 'FunctionProps.FunctionProps(string, Code, Runtime, string)'
```
And finally here's how it looks like when I define a lambda.
```csharp
new Amazon.CDK.AWS.Lambda.Function(this, "SomeId", new FunctionProps(
    handler: "my handler",
    code: Code.Inline("my code"),
    runtime: Runtime.NodeJS810,
    // Optional parameters below: since they have default 
    // values in the constructor, I can omit specifying them.
    //
    // I use a named parameter here but I could also have used 
    // the property setter. It's just a matter of preference.
    // Personally, I prefer to use named constructor parameters 
    // for the optional parameters since they end up at the same 
    // indentation level as the required parameters.
    functionName: "SomeName");
```
Please let me know what you think of this proposition.

### LINKED ISSUE #1904: .NET CDK ignores integration options & method responses in API Gateway methods
Regardless what is set in **MethodResponses** and **IntegrationOptions**, the cdk synth command output cloud formation wouldn't have those configuration as part of its Cloud Formation output when using cdk for .NET.

### Here is the .NET C# code, you can see there are some configurations related to Status code 200 ##

```            
            var serviceResourceMethodResponses = new Dictionary<string, object>[] { new Dictionary<string, object>()};
            serviceResourceMethodResponses[0].Add("StatusCode", "200");
            serviceResourceMethodResponses[0].Add("ResponseModels", new Dictionary<string, string> { { "application/json", "Empty" } });
```
            var integrationResponseOptions = new IntegrationOptions
            {
                IntegrationResponses = new IntegrationResponse[] { new IntegrationResponse {
                            StatusCode = "200",
                            ResponseTemplates = new Dictionary<string, string> { {"application/json", "" } }
                }}
            };
```
            var serviceGet = new CfnMethod_(this, "serviceGetId", new CfnMethodProps
            {
                HttpMethod = "GET",
                Integration = new IntegrationProps
                {
                    Type = IntegrationType.AwsProxy,
                    Options = integrationResponseOptions,
                    IntegrationHttpMethod = "GET",
                    Uri = $"arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/{DemoAPIG.FunctionArn}/invocations"
                },
                ResourceId = serviceResource.ResourceId,
                ApiKeyRequired = false,
                AuthorizationType = "AWS_IAM",
                RestApiId = apigForWorkDocsGoService.RestApiId,
                MethodResponses = serviceResourceMethodResponses
            });
            serviceGet.AddDependsOn(serviceResource);
```

### Here is the Cloud Formation Output from cdk synth command and no integration configuration nor the method response configuration
```
  serviceGetId:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: serviceResourceId
      RestApiId:
        Ref: apigForDemoServiceId
      ApiKeyRequired: false
      AuthorizationType: AWS_IAM
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - DemoAPIGId
                  - Arn
              - /invocations
    DependsOn:
      - serviceResourceId
    Metadata:
      aws:cdk:path: nrt-prod/serviceGetId
```

### LINKED ISSUE #4966: invoking add_ingress_rule() on an imported security group throws AttributeError: 'Resource' object has no attribute 'add_ingress_rule'
After upgrading CDK to v1.16.x and jsii to 0.20.3 today, add_ingress_rule() suddenly started throwing the below error when trying to add an inbound rule to an imported security group.

AttributeError: 'Resource' object has no attribute 'add_ingress_rule'

### Reproduction Steps

```python
self._lambda_security_group = ec2.SecurityGroup.from_security_group_id(
    self,
    'sg1',
    security_group_id='sg-xxxx'
)

self._lambda_security_group.add_ingress_rule(
    ec2.Peer().prefix_list('sg-xxxx'),
    ec2.Port.tcp(443),
    description="Sample Ingress rule"
)
```

### Error Log

```
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    env=core.Environment(account=ES_DOMAIN_ARN.split(":")[4], region=ES_DOMAIN_ARN.split(":")[3])
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/aws_es_recommended_cw_alarms/aws_es_recommended_cw_alarms_stack.py", line 23, in __init__
    self, "aws-es-cw-alarms", domain_arn, aws_cli_profile, cw_trigger_sns_arn_list, enable_es_api_output, es_api_output_sns_arn
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/aws_es_recommended_cw_alarms/aws_es_cw_alarms.py", line 220, in __init__
    self._lambda_security_group.add_ingress_rule(
AttributeError: 'Resource' object has no attribute 'add_ingress_rule'
```

### Environment

  - **CLI Version      :** 1.16.1 (build 9a5a761)
  - **Framework Version:**
  - **OS               :** macOS Sierra
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #4989: .NET CDK 1.16.2 JsiiException exception on synth at CodeCommit.Repository.OnCommit
After upgrading my working simple CI/CD CDK project from .NET CDK 1.11.0 to CDK 1.16.2, I started getting an exception with message:

> Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: System.InvalidCastException: Unable to cast Amazon.JSII.Runtime.Deputy.AnonymousObject into Amazon.CDK.AWS.Events.IOnEventOptions

### Reproduction Steps
Plug the snippet below into your .NET CDK project and run it to see the exception.

```cs
private static Pipeline CreateCiCdPipeline(Construct parent)
{
    const string appName = "My-Application";

    Artifact_ sourceCodeArtifact = new Artifact_("Visual-Studio-Solution");

    Vcs.Repository gitRepo = new Vcs.Repository(parent, "CodeCommitRepo",
        new Vcs.RepositoryProps
        {
            RepositoryName = "My-CodeCommit-Repo",
            Description = $"Version control system for {appName} application"
        }
    );

    var buildPipeline = new Pipeline(parent, "BuildPipeline",
        new PipelineProps
        {
            PipelineName = appName,
            Stages = new[]
            {
                new StageProps
                {
                    StageName = "Source",
                    Actions = new [] {
                        new CodeCommitSourceAction(new CodeCommitSourceActionProps
                        {
                            ActionName = "Git-checkout-from-CodeCommit-repo",
                            Repository = gitRepo,
                            Output = sourceCodeArtifact,
                            Branch = "master",
                        })
                    }
                }
            }
        }
    );

    return buildPipeline;
}
```

### Error Log

> Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: System.InvalidCastException: Unable to cast Amazon.JSII.Runtime.Deputy.AnonymousObject into Amazon.CDK.AWS.Events.IOnEventOptions

### Environment

  - **CLI Version      :*1.16.2 (build 5893301)*
  - **Framework Version:*3.0*
  - **OS               :*Windows 10 Build 17763.805*
  - **Language         :*C#*

#### Stack Trace

Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: System.InvalidCastException: Unable to cast Amazon.JSII.Runtime.Deputy.AnonymousObject into Amazon.CDK.AWS.Events.IOnEventOptions
   at Amazon.JSII.Runtime.Deputy.DeputyBase.ToType(Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Amazon.JSII.Runtime.Services.Converters.JsiiToFrameworkConverter.TryConvertClass(Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.CallbackExtensions.<>c__DisplayClass2_0.<InvokeMethod>b__0(Int32 n)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeMethod(InvokeRequest request, IReferenceMap referenceMap)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallbackCore(Callback callback, IReferenceMap referenceMap)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallback(Callback callback, IReferenceMap referenceMap, IFrameworkToJsiiConverter converter, String& error)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.CodeCommit.Repository.OnCommit(String id, IOnCommitOptions options)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.CodePipeline.Actions.CodeCommitSourceAction.Bound(Construct scope, IStage stage, IActionBindOptions options)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.CodePipeline.Actions.Action.Bind(Construct scope, IStage stage, IActionBindOptions options)

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by RomainMuller**
1. Upgrades `jsii` to `0.20.5`(fixes #4989, fixes #4966, fixes #1904, fixes #1845)
2. Fixes the `ecs-patterns` library bug #4983
3. Fixes the CLI's "legacy" mode of operation bug #4998

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by RomainMuller** [comment]
@eladb  - amended commit chain to include that (I'll be updating the main description now, too)
