### ISSUE TITLE
aws-cdk: Fn.find_in_map default_value not working in version 2.92.0

### ISSUE THREAD

**Issue by drobbins-ancile** [aws/aws-cdk#26843]
### Describe the bug

I am attempting to use the new `default_value` behavior that was added in 2.91.0 ([#26543](https://github.com/aws/aws-cdk/pull/26543)) and receiving `TypeError: Fn.find_in_map() got an unexpected keyword argument 'default_value'` when synthesizing in an AWS CodeBuild project.

Code:

```
"SUMO_HTTP_ENDPOINT": Fn.find_in_map(
    map_name="SumoLogEndpointMapping",
    top_level_key=Fn.sub("${AWS::Region}"),
    second_level_key=environment_identifier,
    default_value="https://collectors.sumologic.com/receiver/v1/http/ZaVnC4dhaV1w186NMo7tSCtg2WkVlLJuOnn3fLHQVBNG_7-rAMTESF8WXfvgvI9JNThMJXDtarakXHXiikuTsWmTbtuxWNR-7KcsyoYupy7uowmxO7s_eA==",
),
```

The build project shows the CDK version:
```
cdk --version
2.92.0 (build bf62e55)
```

I was asked to create this issue by AWS Support as they were able to replicate the error message as well.

### Expected Behavior

The template successfully synthesizes using the mapping with a default value.

### Current Behavior

Synthesize fails with `TypeError: Fn.find_in_map() got an unexpected keyword argument 'default_value'`.

### Reproduction Steps

Create a mapping:

```
  cdk.CfnMapping(
      self,
      "SumoLogEndpointMapping",
      mapping={
          "us-east-1": {
              "Dev": "https://collectors.sumologic.com/receiver/v1/http/ZaVnC4dhaV2zVTIbTl6Q5l5Y5y6BldZgrQTXxwNS7uobzEOcGhKUftWzW9cwXEzHjl8AKpgAvzGmKeVVhy2uK1PgIahFv4Ge1_VSWgQZ36xc7Uj108obQQ==",
	}
      },
  )
````

Attempt to set a value using `Fn.find_in_map`:
```
  "SUMO_HTTP_ENDPOINT": Fn.find_in_map(
      map_name="SumoLogEndpointMapping",
      top_level_key=Fn.sub("${AWS::Region}"),
      second_level_key=environment_identifier,
      default_value="https://collectors.sumologic.com/receiver/v1/http/ZaVnC4dhaV1w186NMo7tSCtg2WkVlLJuOnn3fLHQVBNG_7-rAMTESF8WXfvgvI9JNThMJXDtarakXHXiikuTsWmTbtuxWNR-7KcsyoYupy7elomxO7s_eA==",
  ),
```

### CDK CLI Version

2.92.0 (build bf62e55)

### Node.js Version

16

### OS

AWS Linux (CodeBuild aws/codebuild/standard:6.0)

### Language

Python

### Language Version

3.10

**Comment by peterwoodworth** [comment]
Is this only occurring for you in Codebuild? If so, are you sure that your codebuild `aws-cdk-lib` version is at `2.92.0` as well? You would need to check that the dependencies are actually using the new version, it's not enough for just the CLI to be at `2.92.0` depending on your build commands.

If that isn't an issue, please provide a working reproduction which I'd be able to copy+paste and reproduce the error with.

**Comment by scanlonp** [comment]
Additionally, does the error still occur if you use `CfnMapping.find_in_map()` instead of `Fn.find_in_map()`?
