### PR TITLE
feat(codepipeline): pipeline type v2 with pipeline-level variables and triggers

### LINKED ISSUE #28476: (codepipeline): Pipeline should allow pipelineType and variables passthrough to underlying CfnPipeline construct
### Describe the feature

some case pipelineType "V2" is more cost  effective.

I want to use Pipeline-level variables for manual trigger pipeline.

https://docs.aws.amazon.com/codepipeline/latest/userguide/pipeline-types-planning.html

https://aws.amazon.com/codepipeline/pricing/

### Use Case

We have large Infrastructure. We want partial deploy.

use Manual trigger with Pipeline level variables and set deploy target through variables.
 

### Proposed Solution

add pipelineType and variables to pipelineProps,

pipeline validate  variables should set pipelineType "V2"

passthrough these to CfnPipeline

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.116.1

### Environment details (OS name and version, etc.)

windows 11

### PR DESCRIPTION
**Pull request by go-to-k**
This PR supports pipeline type v2 with pipeline-level variables and triggers.

When referring to a variable in pipeline actions, it must be specified according to the format `#{variables.variableName}`. In order to avoid the need to specify directly in this form, a new class `Variable` with a `reference()` method was created.

```ts
const myVariable = new codepipeline.Variable({
  variableName: 'bucket-var',
  description: 'description',
  defaultValue: 'sample',
});

const pipeline = new codepipeline.Pipeline(stack, 'Pipeline', {
  artifactBucket: sourceBucket,
  pipelineType: codepipeline.PipelineType.V2,
  variables: [myVariable],
  stages: [
    {
      stageName: 'Source',
      actions: [sourceAction],
    },
    {
      stageName: 'Deploy',
      actions: [
        new S3DeployAction({
          actionName: 'DeployAction',
          extract: false,
          // objectKey: '#{variables.bucket-var}.txt',
          objectKey: `${myVariable.reference()}.txt`,
          input: sourceOutput,
          bucket: deployBucket,
        }),
      ],
    },
  ],
});
```

- user guide
  - https://docs.aws.amazon.com/codepipeline/latest/userguide/pipeline-types-planning.html
  - https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html#reference-variables-workflow
  - https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-github-tags.html
- CloudFormation
  - https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  - https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-variabledeclaration.html
  - https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-pipelinetriggerdeclaration.html

Closes #28476 #28694.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 1]
```diff
@@ -419,6 +421,50 @@ for details on how to use the variables for each action class.
...
+      stageName: 'Source',
+      actions: [sourceAction],
+    },
+    {
+      stageName: 'Deploy',
+      actions: [
+        new codepipeline_actions.S3DeployAction({
+          actionName: 'DeployAction',
+          // can reference the variables
+          objectKey: '#{variables.bucket-var}.txt',
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:458]: I had the idea of making variables a class to hide this notation (`#{variables.xxx}`), so I will change this PR to draft.

**Comment by go-to-k** [comment]
waiting this.

https://github.com/aws/aws-cdk/pull/28542

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 2]
```diff
@@ -92,6 +92,93 @@ export interface StageOptions extends StageProps {
...
+    if (
+      this.defaultValue !== undefined
+      && !Token.isUnresolved(this.defaultValue)
+      && (this.defaultValue.length < 1 || this.defaultValue.length > 1000)
+    ) {
+      throw new Error(`Default value for variable '${this.variableName}' must be between 1 and 1000 characters long, got ${this.defaultValue.length}`);
+    }
+    if (this.description !== undefined && !Token.isUnresolved(this.description) && this.description.length > 200) {
+      throw new Error(`Description for variable '${this.variableName}' must not be greater than 200 characters long, got ${this.description.length}`);
+    }
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:158]: Only the validation of `variableName` is defined in a separate file (`packages/aws-cdk-lib/aws-codepipeline/lib/private/validation.ts`) in order to use existing methods for regular expressions.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 3]
```diff
@@ -373,6 +478,8 @@ export class Pipeline extends PipelineBase {
   private readonly enableKeyRotation?: boolean;
   private readonly reuseCrossRegionSupportStacks: boolean;
   private readonly codePipeline: CfnPipeline;
+  private readonly pipelineType?: PipelineType;
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:481]: To prevent changes from occurring with the existing version of the template, this parameter is made optional rather than overwritten by V1 when unspecified in props.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 4]
```diff
@@ -590,6 +711,7 @@ export class Pipeline extends PipelineBase {
       ...this.validateHasStages(),
       ...this.validateStages(),
       ...this.validateArtifacts(),
+      ...this.validateVariables(),
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:714]: Considering that elements are added to `variables` later with the `addVariable` method as well as constructor, I defined them in the `validatePipeline` method called in `node.addValidation`.

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 5]
```diff
@@ -419,6 +421,52 @@ for details on how to use the variables for each action class.
...
 
+### Pipeline-level variables
+
+You can add one or more variables at the pipeline level. You can reference
+this value in the configuration of CodePipeline actions. You can add the
+variable names, default values, and descriptions when you create the pipeline.
+Variables are resolved at the time of execution.
+
+Note that using pipeline-level variables in any kind of Source action is not supported.
+Also, the variables can only used with pipeline type V2.
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:432]:
```suggestion
Also, the variables can only be used with pipeline type V2.
```

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 6]
```diff
@@ -92,6 +92,96 @@ export interface StageOptions extends StageProps {
...
+    if (
+      this.defaultValue !== undefined
+      && !Token.isUnresolved(this.defaultValue)
+      && (this.defaultValue.length < 1 || this.defaultValue.length > 1000)
+    ) {
+      throw new Error(`Default value for variable '${this.variableName}' must be between 1 and 1000 characters long, got ${this.defaultValue.length}`);
+    }
+    if (this.description !== undefined && !Token.isUnresolved(this.description) && this.description.length > 200) {
+      throw new Error(`Description for variable '${this.variableName}' must not be greater than 200 characters long, got ${this.description.length}`);
+    }
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:161]: Only the validation of `variableName` is defined in a separate file (`packages/aws-cdk-lib/aws-codepipeline/lib/private/validation.ts`) in order to use an existing method for regular expressions.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 7]
```diff
@@ -373,6 +481,8 @@ export class Pipeline extends PipelineBase {
   private readonly enableKeyRotation?: boolean;
   private readonly reuseCrossRegionSupportStacks: boolean;
   private readonly codePipeline: CfnPipeline;
+  private readonly pipelineType?: PipelineType;
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:484]: To prevent changes from occurring with the existing version of the template, this parameter is made optional rather than overwritten by V1 when unspecified in props.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 8]
```diff
@@ -590,6 +714,7 @@ export class Pipeline extends PipelineBase {
       ...this.validateHasStages(),
       ...this.validateStages(),
       ...this.validateArtifacts(),
+      ...this.validateVariables(),
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:717]: Considering that elements are added to `variables` later with the `addVariable` method as well as constructor, I defined this in the `validatePipeline` method called in `node.addValidation`.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts (hunk 7 above)
Comment (mrgrain) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:484]: We can always set the the internal prop, just don't set it on the CfnPipeline.

Comment (mrgrain) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:484]: Let's also throw a dismissible warning if pipeline type is not set.

**Review by mrgrain — DISMISSED** [review]
How about instead of adding this as a property, we create a new class `PipelineV2`? Also because the pricing model is so different. I appreciate this will require more refactoring of the existing code. What do you think? 

@kaizencc What are your thoughts?

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts (hunk 7 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts]: @mrgrain 

I changed them.

> We can always set the the internal prop, just don't set it on the CfnPipeline.

https://github.com/aws/aws-cdk/pull/28538/commits/3e799832c7f6d1f7d69613570afa17dca35ad727

> Let's also throw a dismissible warning if pipeline type is not set.

https://github.com/aws/aws-cdk/pull/28538/commits/529786ad335c5514937d9a0e43ff3b645bf10480

**Comment by go-to-k** [comment]
@mrgrain 

> How about instead of adding this as a property, we create a new class PipelineV2? Also because the pricing model is so different. I appreciate this will require more refactoring of the existing code. What do you think?

Currently, all the components are the same except for `variables`, so I feel that there is little benefit. If we want to use V2, just specify V2 in `pipelineType` in the current code. Also, it may be difficult to deal with new V3 when it appears someday.

**Comment by go-to-k** [comment]
I added trigger feature.

**Comment by AllanOricil** [comment]
when is this going to be released?

**Comment by Tochey** [comment]
> when is this going to be released? I would like to use variables and trigger on pushing a tag

+1

**Comment by go-to-k** [comment]
@mrgrain 
Could you please take a look the changes again?

@AllanOricil 
We are waiting for the maintainer's review, so please wait a little longer.

**Comment by mrgrain** [comment]
@kaizencc  I'm happy with this but don't have to time to do a full review at the moment. Can you take over?

**Comment by glc-omid** [comment]
hello ;) will have this pull request any chance of release?

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 9]
```diff
@@ -419,6 +421,52 @@ for details on how to use the variables for each action class.
...
 for more details on how to use the variables feature.
 
+### Pipeline-level variables
+
+You can add one or more variables at the pipeline level. You can reference
+this value in the configuration of CodePipeline actions. You can add the
+variable names, default values, and descriptions when you create the pipeline.
+Variables are resolved at the time of execution.
+
+Note that using pipeline-level variables in any kind of Source action is not supported.
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:431]: I'm confused about this sentence. it makes sense, because we're talking about pipeline-level variables and not action-level variables. Just via the name, I'd assume that pipeline-level variables are unusable in any kind of action (not just source actions). Is that a correct assumption?

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 10]
```diff
@@ -365,6 +365,8 @@ const replicationBucket = new s3.Bucket(replicationStack, 'ReplicationBucket', {
 
 ## Variables
 
+### Action-level variables
+
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:369]: Can we go over the existing README for variables and make sure that they are clear about it being action-level?

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 11]
```diff
@@ -479,3 +527,41 @@ const target = new chatbot.SlackChannelConfiguration(this, 'MySlackChannel', {
 declare const pipeline: codepipeline.Pipeline;
 const rule = pipeline.notifyOnExecutionStateChange('NotifyOnExecutionStateChange', target);
 ```
+
+## Trigger
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:531]: Separate feature, separate PR imo. Unless you can convince me that these are somehow intertwined. Think about if we have to revert, we don't want to have to revert everything just because they were bundled together in one PR

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 12]
```diff
@@ -92,6 +93,184 @@ export interface StageOptions extends StageProps {
...
+   */
+  V1 = 'V1',
+  /**
+   * V2 type
+   */
+  V2 = 'V2',
+}
+
+/**
+ * Properties of pipeline-Level variable.
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:111]:
```suggestion
 * Properties of pipeline-level variable.
```

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 13]
```diff
@@ -173,6 +352,37 @@ export interface PipelineProps {
...
+  readonly pipelineType?: PipelineType;
+
+  /**
+   * A list that defines the pipeline variables for a pipeline resource.
+   *
+   * `variables` can only be used when `pipelineType` is set to `PipelineType.V2`.
+   *
+   * @default - No variables
+   */
+  readonly variables?: Variable[]
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:372]:
```suggestion
  readonly variables?: Variable[];
```

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 14]
```diff
@@ -173,6 +352,37 @@ export interface PipelineProps {
...
+   * starts the pipeline.
+   *
+   * When a trigger configuration is specified, default change detection for repository
+   * and branch commits is disabled.
+   *
+   * `triggers` can only be used when `pipelineType` is set to `PipelineType.V2`.
+   *
+   * @default - No triggers
+   */
+  readonly triggers?: Trigger[]
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:385]:
```suggestion
  readonly triggers?: Trigger[];
```

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 15]
```diff
@@ -434,13 +646,22 @@ export class Pipeline extends PipelineBase {
       assumedBy: new iam.ServicePrincipal('codepipeline.amazonaws.com'),
     });
 
+    if (props.pipelineType === undefined) {
+      Annotations.of(this).addWarningV2('@aws-cdk/aws-codepipeline:unspecifiedPipelineType', 'V1 pipeline type is implicitly selected when `pipelineType` is not set. If you want to use V2 type, set `PipelineType.V2`.');
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:650]: Musings (for a separate PR): should we add a feature flag that changes the default pipeline to be v2?

File: packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts [hunk 16]
```diff
@@ -496,6 +497,545 @@ describe('', () => {
...
+        })],
+      });
+
+      pipeline.addStage({
+        stageName: 'Build',
+        actions: [new FakeBuildAction({
+          actionName: 'FakeBuild',
+          input: sourceArtifact,
+        })],
+      });
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts:561]: We're duplicating this in at least 2 places. Lets pull it out into a `testPipelineSetup` method or put it all in a `describe` block with `test.beforeEach`, or both

File: packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts [hunk 17]
```diff
@@ -171,11 +171,11 @@ test('Policy sizes do not exceed the maximum size', () => {
     }
   }
 
-  // expect template size warning, but no other warnings
+  // expect template size warning
   const annotations = Annotations.fromStack(pipelineStack);
   annotations.hasWarning('*', Match.stringLikeRegexp('^Template size is approaching limit'));
   const warnings = annotations.findWarning('*', Match.anyValue());
-  expect(warnings.length).toEqual(1);
+  expect(warnings.length).toEqual(2); // including warning of unspecified pipeline type in the internal pipeline construct
```
Comment (kaizencc) [inline packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts:178]: we should assert on the specific warning name, not the length of the warnings

File: packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts [hunk 18]
```diff
@@ -496,6 +497,545 @@ describe('', () => {
...
+            gitConfiguration: {
+              sourceAction,
+              pushFilter: [{
+                excludedTags: ['exclude1', 'exclude2'],
+                includedTags: ['include1', 'include2'],
+              }],
+            },
+          }],
+        });
+      }).toThrow(/provider for actionProperties in sourceAction must be 'CodeStarSourceConnection', got 'Fake' at triggers\[0\]/);
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/test/pipeline.test.ts:1009]: I'm confused by this test:

1) this looks like an additional requirement, is it documented anywhere
2) it says got 'Fake'. I don't see where we specified the provider to be `fake` so this confuses me.

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 19]
```diff
@@ -1077,6 +1315,56 @@ export class Pipeline extends PipelineBase {
...
+    return this.variables.map(variable => variable._render());
+  }
+
+  private renderTriggers(triggers?: Trigger[]): CfnPipeline.PipelineTriggerDeclarationProperty[] | undefined {
+    if (triggers === undefined || triggers.length === 0) {
+      return;
+    }
+
+    if (this.pipelineType !== PipelineType.V2) {
+      throw new Error('triggers can only be used with V2 pipelines');
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:1328]: should also say how to specify V2 pipelines

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 20]
```diff
@@ -1017,6 +1248,13 @@ export class Pipeline extends PipelineBase {
     return ret;
   }
 
+  private validateVariables(): string[] {
+    if (this.variables.length && this.pipelineType !== PipelineType.V2) {
+      return ['Pipeline variables can only be used with V2 pipelines'];
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:1253]: should specify how to specify V2 pipelines.

**Review by kaizencc — CHANGES_REQUESTED** [review]
A few comments here and there. Ideally I would like variables and triggers to be separate PRs as they are separate features. But maybe there's a compelling reason to put them together.

Also to ponder: whats the story for migrating your pipeline from v1 to v2? If that is not as simple as specifying `pipelineType: V2` then adding these props onto the V1 pipeline construct will be painful for users who are so close yet so far to being able to use them.

Note to self: I did not look at integ tests yet

File: packages/aws-cdk-lib/aws-codepipeline/README.md (hunk 11 above)
Comment (glc-omid) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:531]: I think we need to see the cdk logic in the same way of pipeline features, 

V2 is actually V1 plus variables and tag triggers, 

Maybe extending V1 to cover v2 can be elegant instead of changing V1 

Also by just adding pipeline type v2 you can cover the tag feature

Variables can go along separately.

**Review by go-to-k — COMMENTED** [review]
@kaizencc

> A few comments here and there. Ideally I would like variables and triggers to be separate PRs as they are separate features. But maybe there's a compelling reason to put them together.

Yes. Originally, this PR was only going to support variables, but I only added it because I found an issue later that wanted support for triggers. In other words, we can have separate PRs. But for now, I'm still going to make edits in the same PR and go through all the reviews and agreement on policies before making them separate PRs.

> Also to ponder: whats the story for migrating your pipeline from v1 to v2? If that is not as simple as specifying pipelineType: V2 then adding these props onto the V1 pipeline construct will be painful for users who are so close yet so far to being able to use them.

We can just change from V1 to V2 by changing `props.pipelineType` from `PipelineType.V1` to `PipelineType.V2` only like AWS console for CodePipeline.
Separate construct/props from V1 would compromise compatibility and ease of migration for existing users, so I think it is good that both the construct and props are the same as V1.

**Comment by go-to-k** [comment]
@kaizencc 

All comments are reflected or commented back. I would be happy to have them checked.

**Comment by go-to-k** [comment]
@kaizencc 

I have a question for you.

The current PR consists of three components: the V2 introduction, the pipeline variable, and the trigger.

When separating the PRs, instead of dividing them into these three, can one consist of the V2 introduction and pipeline variables and the other of the triggers, as I feel it is too small to have one PR for the V2 introduction.

**Comment by go-to-k** [comment]
@kaizencc 

All comments are reflected or commented back. I would be happy to have them checked.

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 21]
```diff
@@ -365,6 +365,8 @@ const replicationBucket = new s3.Bucket(replicationStack, 'ReplicationBucket', {
 
 ## Variables
 
+### Action-level variables
+
 The library supports the CodePipeline Variables feature.
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:370]:
```suggestion
The library supports action-level variables.
```

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 22]
```diff
@@ -365,6 +365,8 @@ const replicationBucket = new s3.Bucket(replicationStack, 'ReplicationBucket', {
 
 ## Variables
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:366]: Lets have a few sentences here describing what the different scopes mean for variables

File: packages/aws-cdk-lib/aws-codepipeline/README.md (hunk 9 above)
Comment (kaizencc) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:431]: My confusion is that pipeline-level variables cannot be USED in source action but can be USED elsewhere. Of course. the scope of pipeline-level is the level its defined in, not where its used in. My bad

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 23]
```diff
@@ -419,6 +421,52 @@ for details on how to use the variables for each action class.
 See the [CodePipeline documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html)
 for more details on how to use the variables feature.
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/README.md:422]: Lets add an example for an action-level variable here too to have parity with the pipeline-level section

File: packages/aws-cdk-lib/aws-codepipeline/README.md (hunk 11 above)
Comment (kaizencc) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:531]: Lets just keep it all together

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts [hunk 24]
```diff
@@ -92,6 +93,184 @@ export interface StageOptions extends StageProps {
...
+  /**
+   * V2 type
+   */
+  V2 = 'V2',
+}
+
+/**
+ * Properties of pipeline-level variable.
+ */
+export interface VariableProps {
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:113]: Lets put variable code into `variable.ts` and trigger code into `trigger.ts`

File: packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts [hunk 25]
```diff
@@ -0,0 +1,61 @@
...
+import { IntegTest } from '@aws-cdk/integ-tests-alpha';
+import * as cpactions from 'aws-cdk-lib/aws-codepipeline-actions';
+
+const app = new cdk.App();
+
+const stack = new cdk.Stack(app, 'aws-cdk-codepipeline-with-pipeline-triggers');
+
+const sourceOutput = new codepipeline.Artifact();
+// Make sure you specify a valid connection ARN.
+const connectionArn = process.env.CONNECTION_ARN || 'MOCK';
```
Comment (kaizencc) [inline packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts:13]: I'm assuming you grabbed this from elsewhere in this module. Wonder if we can at least provide a synth-time warning here to alert people manually running this integ test. 

I sense that what usually happens is that I will run the integ test, it will fail at deploy time, and then I have to go searching for why. Having a warning show up on console would at least give me a fighting chance of identifying the issue pre-deploy. what do you think?

**Review by kaizencc — CHANGES_REQUESTED** [review]
Thanks @go-to-k. I have a few comments mostly just on documentation. Otherwise i think this is good. Thanks for your contributions!

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts (hunk 24 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts]: I separated the files and test files.

https://github.com/aws/aws-cdk/pull/28538/commits/1b4bc2108900f464811cce7cad75acdb357fb5e6

Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts]: The trigger is an interface, not a class. Is it okay if I have them in separate files?

File: packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts (hunk 15 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:490]: OK, I will change the default type to V2 under feature flag.

Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/pipeline.ts:491]: https://github.com/aws/aws-cdk/pull/28538/commits/403d7fa92173fb1fef3628396ba3fb67cb49758e

File: packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts [hunk 26]
```diff
@@ -0,0 +1,61 @@
...
+        includedTags: ['include1', 'include2'],
+      }],
+    },
+  }],
+});
+
+new IntegTest(app, 'codepipeline-with-pipeline-triggers-test', {
+  testCases: [stack],
+  diffAssets: true,
+});
```
[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/@aws-cdk-testing/framework-integ/test/aws-codepipeline-actions/test/integ.pipeline-with-pipeline-triggers.ts:61]: I added the assertion to check if the pipeline has been deployed. There seemed to be no further assertions.

https://github.com/aws/aws-cdk/pull/28538/commits/69a0e769d2e333d18681535b78ee6fdad144de45

```ts
const awsApiCall = integrationTest.assertions.awsApiCall('CodePipeline', 'getPipeline', { name: 'my-pipeline' });
awsApiCall.assertAtPath('pipeline.name', ExpectedResult.stringLikeRegexp('my-pipeline'));
```

File: packages/aws-cdk-lib/aws-codepipeline/README.md [hunk 27]
```diff
@@ -479,3 +527,41 @@ const target = new chatbot.SlackChannelConfiguration(this, 'MySlackChannel', {
...
+
+The triggers can only be used with pipeline type V2.
+
+```ts
+declare const sourceOutput: codepipeline.Artifact;
+declare const sourceAction: codepipeline_actions.CodeStarConnectionsSourceAction;
+declare const buildAction: codepipeline_actions.CodeBuildAction;
+
+new codepipeline.Pipeline(this, 'Pipeline', {
+  pipelineType: codepipeline.PipelineType.V2,
```
[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:544]: I added.
https://github.com/aws/aws-cdk/pull/28538/commits/74eb13e0c1930c76f6ffb9da7beb753d37af73ce

File: packages/aws-cdk-lib/aws-codepipeline/README.md (hunk 23 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:451]: I added. 

https://github.com/aws/aws-cdk/pull/28538/commits/b2a03e7b69a7199c37e86df9e56a87204882cf5d

File: packages/aws-cdk-lib/aws-codepipeline/README.md (hunk 22 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/README.md:366]: https://github.com/aws/aws-cdk/pull/28538/commits/f20a00cb4110265e3254cd1ae250c9c1b73799ea

**Comment by go-to-k** [comment]
@kaizencc 

Thanks again for the review. I think I probably could have reflected all comments. Would you please check again.

**Comment by angel3cu** [comment]
Hey! Thank you for making this PR. 😄

It seems it has been stuck in the review phase for a while now and the change is important my company's workflow (see [issue](https://github.com/aws/aws-cdk/issues/28694) I raised a while ago). Any estimate on roughly when this can be merged/released? Thanks! 🙂

**Comment by go-to-k** [comment]
@angel3cu
Thanks for waiting so long. Depending on the maintainer review, I (or we) don't have a specific timeline as I'm sure they will have many other tasks as well. However, we are nearing the end of the exchange of reviews, so I think we are getting close. Please wait a little longer. (There are a lot of reactions to the issue, and it must surely be a high priority among them.)

**Comment by angel3cu** [comment]
No worries. Thanks for letting me know and for raising the PR @go-to-k. 🙂

File: packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts [hunk 28]
```diff
@@ -0,0 +1,160 @@
...
+   * criteria that starts the pipeline.
+   *
+   * You can filter with glob patterns. The `excludedTags` takes priority
+   * over the `includedTags`.
+   *
+   * Maximum length of this array is 8.
+   *
+   * @default - no tags.
+   */
+  readonly includedTags?: string[];
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts:32]: In the original CFn, [GitPushFilter](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-gitpushfilter.html) has `Tags`, and `Tags` has `Excludes` and `Includes`. However, the nesting is erased along [DESIGN_GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#flat).

I originally thought this was good, but today the trigger has [new feature](https://aws.amazon.com/jp/blogs/devops/aws-codepipeline-adds-support-for-branch-based-development-and-monorepos/) was added. It allows users to trigger branches as well as tags.

This feature has not yet been introduced to CFn, but perhaps like `Tags`, a property called `Branches` will be added to the `GitPushFilter`, which will also have `Excludes` and `Includes`. Considering this, I also thought it might be better to dare to nest `GitPushFilter` and have `GitTagFilterCriteria`.

Otherwise, the code would probably look something like this. (I am not even sure if this is a bad idea. I am thinking that it would be better to at least have a common prefix for each of them.)

```ts
export interface GitPushFilter {
  readonly excludedTags?: string[];
  readonly includedTags?: string[];
  readonly excludedBranches?: string[];
  readonly includedBranches?: string[];
  readonly excludedFilePaths?: string[];
  readonly includedFilePaths?: string[];
```

Comment (go-to-k) [reply packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts]: I changed the property names for now: [change names to tagsExcludes and tagsIncludes](https://github.com/aws/aws-cdk/pull/28538/commits/95d17124c91cea2d2d7a1fef60a8abe6b13b4a9c)

If `Branches` is added as is, it would look like this:

```ts
export interface GitPushFilter {
  readonly tagsExcludes?: string[];
  readonly tagsIncludes?: string[];
  readonly branchesExcludes?: string[];
  readonly branchesIncludes?: string[];
  readonly filePathsExcludes?: string[];
  readonly filePathsIncludes?: string[];
```

**Comment by go-to-k** [comment]
@kaizencc 

I have changed the followings as well as your comments. Could you please confirm them?

- [add validation for length of gitPushFilter](https://github.com/aws/aws-cdk/pull/28538/commits/52a8efb6be4b205ff922bdd11b19eaa9efd65a95)
- [add `addTrigger()` method](https://github.com/aws/aws-cdk/pull/28538/commits/ad9915237602c97adcc9c83e0104f0910ef21524)
- [change `Trigger` from interface to class](https://github.com/aws/aws-cdk/pull/28538/commits/2b3c633a23c2cf27985ea91cc99f8d8a2250bc2f)
- [validate duplicated variables and triggers with duplicate source action](https://github.com/aws/aws-cdk/pull/28538/commits/c201037726e2e4efc5aee51aab4481c9bd7fcec8)
- [change property names to `tagsExcludes` and `tagsIncludes`](https://github.com/aws/aws-cdk/pull/28538/commits/95d17124c91cea2d2d7a1fef60a8abe6b13b4a9c)
  - See [this thread](https://github.com/aws/aws-cdk/pull/28538#discussion_r1485143949)

File: packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts (hunk 28 above)
Comment (kaizencc) [reply packages/aws-cdk-lib/aws-codepipeline/lib/trigger.ts]: I like having what you've proposed.

**Review by kaizencc — APPROVED** [review]
I think this looks great @go-to-k! Thanks for adding these features in!

**Comment by mikelhamer** [comment]
@go-to-k did the typescript type definitions get updated for this? I am on the latest version `2.128.0` but my project won't build due to this error:

`error TS2353: Object literal may only specify known properties, and 'pipelineType' does not exist in type 'CodePipelineProps'.`

**Comment by go-to-k** [comment]
@mikelhamer

Perhaps you have not "npm/yarn install"?

It's working correctly in my environment with v2.128.0.

**Comment by mikelhamer** [comment]
> @mikelhamer
> 
> 
> 
> Perhaps you have not "npm/yarn install"?
> 
> 
> 
> It's working correctly in my environment with v2.128.0.

I realized it's because I'm using the CDK CodePipline construct vs the Pipeline construct this feature you made is for

**Comment by go-to-k** [comment]
I could confirm to work and deploy with the released CDK not in this repository.

**Comment by go-to-k** [comment]
My sample code repository.
https://github.com/go-to-k/cdk-codepipeline-v2-sample
