### PR TITLE
fix(sns): race condition exists between sqs queue policy and sns subscription

### PR DESCRIPTION
**Pull request by jonnekaunisto**
----

Fixes https://github.com/aws/aws-cdk/issues/20665 by adding a dependency to sqs policy for sns subscriptions.
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

This is a follow up to https://github.com/aws/aws-cdk/pull/21259, which got closed for failing for too long

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
This cannot get merged because we can't edit the branch. I am also unable to verify that the tests run locally since I can't download the PR.

Additionally, the follow items weren't confirmed in the PR body:

Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?

Did you use yarn integ to deploy the infrastructure and generate the snapshot (i.e. yarn integ without --dry-run)?

**Comment by jonnekaunisto** [comment]
@TheRealAmazonKendra 

> This cannot get merged because we can't edit the branch. I am also unable to verify that the tests run locally since I can't download the PR.

I'm not sure I understand the problem, how do I fix this?

> Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?

I marked it as completed now, I think the existing integ tests should cover it(Ex. `packages/@aws-cdk/aws-stepfunctions-tasks/test/sns/publish.integ.snapshot/aws-stepfunctions-tasks-sns-publish-integ.template.json`)

> Did you use yarn integ to deploy the infrastructure and generate the snapshot (i.e. yarn integ without --dry-run)?

I will work on doing that.

**Comment by TheRealAmazonKendra** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork 

Looks like you either got this fixed or GitHub was having a hiccup of some sort when I was trying to pull this earlier.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Looks like the merge didn't go quite right.

**Comment by jonnekaunisto** [comment]
Yeah after merging it doesn't let me build anything, because I get errors like this:

```
/workspace/aws-cdk/packages/aws-cdk: yarn build  (25 remaining)
yarn run v1.22.19
$ cdk-build
test/diff.test.ts(265,30): error TS2749: 'StringDecoder' refers to a value, but is being used as a type here. Did you mean 'typeof StringDecoder'?
Error: /workspace/aws-cdk/node_modules/typescript/bin/tsc --build exited with error code 1
```

Any clue how to fix that?

**Comment by TheRealAmazonKendra** [comment]
@Mergifyio update

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Looks like a test is improperly formatted per 
```
@aws-cdk/aws-sns-subscriptions:   ERROR      integ.sns-sqs.lit 1.49s
@aws-cdk/aws-sns-subscriptions:       /codebuild/output/src410239659/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-sns-subscriptions/test/sns-sqs.lit.integ.snapshot/aws-cdk-sns-sqs.template.json: Unexpected token } in JSON at position 965
```
This suggests that they're been manually edited, which  we should not be doing here. Please run the tests with `--update-on-failed` and ensure that the deployment succeeds before committing the resulting change.

**Comment by jonnekaunisto** [comment]
What do I need to do to fix this: `Fixes must contain a change to an integration test file and the resulting snapshot.` 

I did update the integration test files

**Review by TheRealAmazonKendra — APPROVED** [review]

File: packages/@aws-cdk/aws-sns/lib/topic-base.ts [hunk 1]
```diff
@@ -80,8 +80,8 @@ export abstract class TopicBase extends Resource implements ITopic {
   /**
    * Subscribe some endpoint to this topic
    */
-  public addSubscription(subscription: ITopicSubscription): Subscription {
```
Comment (tobytipton) [inline packages/@aws-cdk/aws-sns/lib/topic-base.ts:83]: making a change from `subscription` to `topicSubscription` actually can cause impact this actually breaks in python if you are using named arguments because this changes the argument from `subscription` to `topic_subscription`
