### ISSUE TITLE
(aws-sam): DestinationConfig contains onSuccess property even though it's not part of SAM spec

### ISSUE THREAD

**Issue by GaalDornick** [aws/aws-cdk#16739]
The SAM spec specifies a property called OnSuccess here (https://github.com/aws/aws-cdk/blob/5d0954a2028a001c3c2ed2c7f851c51ca3e82259/packages/%40aws-cdk/cfnspec/spec-source/000_sam.spec.json#L495). However, SAM documentation doesn't specify an OnSuccess property (https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#destination-config-object)

### Reproduction Steps

```
test("correctly creates a function invoked from a dynamodb stream", () => {
 const stack = new cdk.Stack();

  new sam.CfnFunction(stack, 'MyFunction', {
    codeUri: {
      bucket: 'my-bucket',
      key: 'my-key',
    },
    runtime: 'nodejs-12.x',
    handler: 'index.handler',
    policies: ['AWSLambdaExecute'],
    events: {
        MyStream: {
          type: "DynamoDB",
          properties: {
            enabled: true,
            startingPosition: "LATEST",
            stream: "arn:aws:dynamodb:us-east-1:123456789012:table/mytable/stream/2021-08-20T02:52:27.890",
            batchSize: 100,
            maximumBatchingWindowInSeconds: 60, // wait 60 seconds for records to reach batchSize
            maximumRetryAttempts: 2,
            maximumRecordAgeInSeconds: -1, // TODO: Figure out if we should set this value
            bisectBatchOnFunctionError: true,
            destinationConfig: {
              onFailure: {
                destination: "arn:aws:sqs:us-east-1:123456789012:myDLQ.fifo",
              },
              // workaround for possible bug in CDK
              // CDK requires this attribute but doesn't do anything with it
              //onSuccess: {
               // destination: procurementConverterDLQ.dlq.queueArn,
              //},
            },
          },
        },
     }
  });

```

### What did you expect to happen?
I am trying to create a FUnction that gets triggerred from DDB stream. THe above code compiled in v1.106.0 
### What actually happened?
The code doesn't compile in v1.122.0. The error that I get is

```
test/function.test.ts:52:13 - error TS2322: Type '{ onFailure: { destination: string; }; }' is not assignable to type 'IResolvable | DestinationConfigProperty | undefined'.
  Property 'onSuccess' is missing in type '{ onFailure: { destination: string; }; }' but required in type 'DestinationConfigProperty'.

52             destinationConfig: {
               ~~~~~~~~~~~~~~~~~

  lib/sam.generated.ts:2812:18
    2812         readonly onSuccess: CfnFunction.DestinationProperty | cdk.IResolvable;
                          ~~~~~~~~~
    'onSuccess' is declared here.
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other
The DestinationConfig class is in sam.generated.ts which is generated from 000_sam_spec.json. 
I'm not sure how the sam spec gets checked in, but it seems the sam_spec is incorrect

--- 

This is :bug: Bug Report

**Comment by GaalDornick** [comment]
I can submit a fix by updating sam_spec, but I'm not sure if that's the right thing to do

**Comment by GaalDornick** [comment]
This is a bug in GoFormation. I have submitted an issue and a fix in GoFormation repo (https://github.com/awslabs/goformation/issues/404)

This issue can be closed. I'll close it when the fix is merged into GoFormation
