### ISSUE TITLE
invoking add_ingress_rule() on an imported security group throws AttributeError: 'Resource' object has no attribute 'add_ingress_rule'

### ISSUE THREAD

**Issue by aravraje** [aws/aws-cdk#4966]
After upgrading CDK to v1.16.x and jsii to 0.20.3 today, add_ingress_rule() suddenly started throwing the below error when trying to add an inbound rule to an imported security group.

AttributeError: 'Resource' object has no attribute 'add_ingress_rule'

### Reproduction Steps

```python
self._lambda_security_group = ec2.SecurityGroup.from_security_group_id(
    self,
    'sg1',
    security_group_id='sg-xxxx'
)

self._lambda_security_group.add_ingress_rule(
    ec2.Peer().prefix_list('sg-xxxx'),
    ec2.Port.tcp(443),
    description="Sample Ingress rule"
)
```

### Error Log

```
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    env=core.Environment(account=ES_DOMAIN_ARN.split(":")[4], region=ES_DOMAIN_ARN.split(":")[3])
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/aws_es_recommended_cw_alarms/aws_es_recommended_cw_alarms_stack.py", line 23, in __init__
    self, "aws-es-cw-alarms", domain_arn, aws_cli_profile, cw_trigger_sns_arn_list, enable_es_api_output, es_api_output_sns_arn
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/aravraje/aws-solutions/aws-es-recommended-cw-alarms/aws_es_recommended_cw_alarms/aws_es_cw_alarms.py", line 220, in __init__
    self._lambda_security_group.add_ingress_rule(
AttributeError: 'Resource' object has no attribute 'add_ingress_rule'
```

### Environment

  - **CLI Version      :** 1.16.1 (build 9a5a761)
  - **Framework Version:**
  - **OS               :** macOS Sierra
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
I suspect a JSII bug here, @RomainMuller can you see if my hunch is right?

**Comment by aravraje** [comment]
@skinny85 @RomainMuller - I don't see this issue happening in Javascript when I tried replicating using the below .ts code (using CDK v1.16.1):

    const sg = ec2.SecurityGroup.fromSecurityGroupId(
      this,
      'sg1',
      'sg-fc0acb82'
    )

    sg.addIngressRule(
      ec2.Peer.prefixList('sg-fc0acb82'),
      ec2.Port.tcp(443),
      'test inbound rule'
    )

Got the expected output on doing 'cdk diff':

~/a/test ❯❯❯ cdk diff                                                                                                                                                                                                    
Stack TestStack
Security Group Changes

|   | Group | Dir | Protocol | Peer |
| - | ------ | --- | -------- | ---- |
| + | sg-fc0acb82 | In | TCP 443 | sg-fc0acb82 |

(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Conditions
[+] Condition CDKMetadataAvailable: {"Fn::Or":[{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-northeast-2"]},{"Fn::Equals":[{
"Ref":"AWS::Region"},"ap-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ap-southeast-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"ca-central-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"cn-northwest-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-central-1"]}]},{"Fn::Or":[{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-north-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"eu-west-3"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"me-south-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"sa-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-east-2"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-1"]},{"Fn::Equals":[{"Ref":"AWS::Region"},"us-west-2"]}]}]}

Resources
[+] AWS::EC2::SecurityGroupIngress sg1/from sg-fc0acb82:443 sg1fromsgfc0acb824433AACA7C3 

So, probably a JSII bug?

**Comment by johns1342** [comment]
This is also an issue with jsii 0.20.4.

**Comment by RomainMuller** [comment]
Have you also upgraded to CDK `1.16.2`?

**Comment by aravraje** [comment]
I tried with CDK 1.16.2 as well as JSII 0.20.4. Still getting the same error.

(.env) ~/a/aws-es-recommended-cw-alarms ❯❯❯ cdk --version
1.16.2 (build 5893301)

(.env) ~/a/aws-es-recommended-cw-alarms ❯❯❯ pip search jsii
jsii (0.20.4)        - Python client for jsii runtime
  INSTALLED: 0.20.4 (latest)

(.env) ~/a/aws-es-recommended-cw-alarms ❯❯❯ cdk diff
Traceback (most recent call last):
....
....
....
    self._lambda_security_group.add_ingress_rule(
AttributeError: 'Resource' object has no attribute 'add_ingress_rule'
Subprocess exited with error 1

**Comment by RomainMuller** [comment]
Alright I can definitely reproduce this.

**Comment by RomainMuller** [comment]
The result of `from_security_group_id` is serialized as

```js
{"ok":{"result":{"$jsii.byref":"@aws-cdk/core.Resource@10002","$jsii.interfaces":["@aws-cdk/aws-ec2.ISecurityGroup"]}}}
```

This would be the Python jsii runtime *not* correctly using the interfaces list.

**Comment by rix0rrr** [comment]
Probably the wire type negotiation changes

**Comment by RomainMuller** [comment]
Oh it's **definitely** that.

**Comment by rix0rrr** [comment]
I thought we had enough tests there to cover the changes ☹️

**Comment by tarunaroraonline** [comment]
The workaround you've proposed on #4979 goes only so far in being able to get the parameter value from ssm... The overall deployment fails with jsii errors (sepecific error below)...

``` code
      
jsii.errors.JavaScriptError: 
  Error: 'ConnectorsECSStack' object has no attribute 'ref'
      at KernelHost.completeCallback (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7237:27)
      at KernelHost.callbackHandler (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7226:33)
      at Object.value (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7899:41)
      at /tmp/jsii-kernel-78vc3G/node_modules/@aws-cdk/core/lib/construct.js:408:50
      at Array.forEach (<anonymous>)
      at ConstructNode.invokeAspects (/tmp/jsii-kernel-78vc3G/node_modules/@aws-cdk/core/lib/construct.js:408:25)
      at Function.prepare (/tmp/jsii-kernel-78vc3G/node_modules/@aws-cdk/core/lib/construct.js:82:28)
      at Function.synth (/tmp/jsii-kernel-78vc3G/node_modules/@aws-cdk/core/lib/construct.js:51:14)
      at App.synth (/tmp/jsii-kernel-78vc3G/node_modules/@aws-cdk/core/lib/app.js:71:52)
      at Kernel._wrapSandboxCode (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8184:19)
      at /opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7561:25
      at Kernel._ensureSync (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8157:20)
      at Kernel.invoke (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7560:26)
      at KernelHost.processRequest (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7272:28)
      at KernelHost.run (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7212:14)
      at Immediate._onImmediate (/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7215:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 76, in <module>
    run()
  File "app.py", line 50, in run


    run()
  File "app.py", line 50, in run
    app.synth()
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 3468, in synth
    return jsii.invoke(self, "synth", [])
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 107, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 286, in invoke
    return _callback_till_result(self, response, InvokeResponse)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 173, in _callback_till_result
    response = kernel.sync_complete(response.cbid, str(exc), None, response_type)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 329, in sync_complete
    response_type=response_type
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 369, in sync_complete
    resp = self._process.send(_CompleteRequest(complete=request), response_type)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: 'ConnectorsECSStack' object has no attribute 'ref'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:115:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)


```

**Comment by RomainMuller** [comment]
Internal ticket reference: `V154189802`

A fix to the jsii bug was submitted (aws/jsii#980).
It will be released as a matter of urgency.

**Comment by johns1342** [comment]
This appears to be fixed for me using aws-cdk 1.16.2 and jsii 0.20.5.

**Comment by tarunaroraonline** [comment]
@RomainMuller  still seeing this issue after upgrading to the latest version of jsii and aws-cdk 

```
2019-11-13T18:02:58.4168246Z attrs==19.3.0
2019-11-13T18:02:58.4169049Z aws-cdk.assets==1.16.3
2019-11-13T18:02:58.4169356Z aws-cdk.aws-apigateway==1.16.3
2019-11-13T18:02:58.4169593Z aws-cdk.aws-applicationautoscaling==1.16.3
2019-11-13T18:02:58.4169864Z aws-cdk.aws-autoscaling==1.16.3
2019-11-13T18:02:58.4170085Z aws-cdk.aws-autoscaling-common==1.16.3
2019-11-13T18:02:58.4170371Z aws-cdk.aws-autoscaling-hooktargets==1.16.3
2019-11-13T18:02:58.4170600Z aws-cdk.aws-certificatemanager==1.16.3
2019-11-13T18:02:58.4170819Z aws-cdk.aws-cloudformation==1.16.3
2019-11-13T18:02:58.4171078Z aws-cdk.aws-cloudfront==1.16.3
2019-11-13T18:02:58.4171616Z aws-cdk.aws-cloudwatch==1.16.3
2019-11-13T18:02:58.4171879Z aws-cdk.aws-ec2==1.16.3
2019-11-13T18:02:58.4172081Z aws-cdk.aws-ecr==1.16.3
2019-11-13T18:02:58.4172288Z aws-cdk.aws-ecr-assets==1.16.3
2019-11-13T18:02:58.4172539Z aws-cdk.aws-ecs==1.16.3
2019-11-13T18:02:58.4172756Z aws-cdk.aws-elasticloadbalancing==1.16.3
2019-11-13T18:02:58.4173026Z aws-cdk.aws-elasticloadbalancingv2==1.16.3
2019-11-13T18:02:58.4173233Z aws-cdk.aws-events==1.16.3
2019-11-13T18:02:58.4173491Z aws-cdk.aws-iam==1.16.3
2019-11-13T18:02:58.4173696Z aws-cdk.aws-kms==1.16.3
2019-11-13T18:02:58.4173896Z aws-cdk.aws-lambda==1.16.3
2019-11-13T18:02:58.4174145Z aws-cdk.aws-logs==1.16.3
2019-11-13T18:02:58.4174349Z aws-cdk.aws-route53==1.16.3
2019-11-13T18:02:58.4174608Z aws-cdk.aws-route53-targets==1.16.3
2019-11-13T18:02:58.4174818Z aws-cdk.aws-s3==1.16.3
2019-11-13T18:02:58.4175027Z aws-cdk.aws-s3-assets==1.16.3
2019-11-13T18:02:58.4175289Z aws-cdk.aws-secretsmanager==1.16.3
2019-11-13T18:02:58.4175506Z aws-cdk.aws-servicediscovery==1.16.3
2019-11-13T18:02:58.4175764Z aws-cdk.aws-sns==1.16.3
2019-11-13T18:02:58.4175984Z aws-cdk.aws-sns-subscriptions==1.16.3
2019-11-13T18:02:58.4176189Z aws-cdk.aws-sqs==1.16.3
2019-11-13T18:02:58.4176435Z aws-cdk.aws-ssm==1.16.3
2019-11-13T18:02:58.4176632Z aws-cdk.core==1.16.3
2019-11-13T18:02:58.4176876Z aws-cdk.cx-api==1.16.3
2019-11-13T18:02:58.4177080Z aws-cdk.region-info==1.16.3
2019-11-13T18:02:58.4177140Z awscli==1.16.280
2019-11-13T18:02:58.4177245Z botocore==1.13.16
2019-11-13T18:02:58.4177299Z cattrs==0.9.0
2019-11-13T18:02:58.4177395Z Cerberus==1.3.2
2019-11-13T18:02:58.4177448Z colorama==0.4.1
2019-11-13T18:02:58.4177500Z docutils==0.15.2
2019-11-13T18:02:58.4177592Z jmespath==0.9.4
2019-11-13T18:02:58.4177645Z jsii==0.20.5
2019-11-13T18:02:58.4177738Z publication==0.0.3
2019-11-13T18:02:58.4177794Z pyasn1==0.4.7
2019-11-13T18:02:58.4178002Z python-dateutil==2.8.0
2019-11-13T18:02:58.4178106Z PyYAML==5.1.2
2019-11-13T18:02:58.4178157Z rsa==3.4.2
2019-11-13T18:02:58.4178260Z s3transfer==0.2.1
2019-11-13T18:02:58.4178312Z six==1.13.0
2019-11-13T18:02:58.4178517Z typing-extensions==3.7.4.1
2019-11-13T18:02:58.4178620Z urllib3==1.25.7
2019-11-13T18:02:58.9323816Z â„¹ï¸ CDK Version: 1.16.3 (build 8c7f593)
2019-11-13T18:02:58.9328792Z â„¹ï¸ AWS environment variables:
2019-11-13T18:02:58.9330486Z   - AWS_ACCOUNTID = xxxxxx
2019-11-13T18:02:58.9334368Z â„¹ï¸ No CDK environment variables
2019-11-13T18:03:02.7509695Z jsii.errors.JavaScriptError: 
2019-11-13T18:03:02.7511348Z   Error: 'ConnectorsECSStack' object has no attribute 'ref'
2019-11-13T18:03:02.7512196Z       at KernelHost.completeCallback (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7250:27)
2019-11-13T18:03:02.7512856Z       at KernelHost.callbackHandler (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:33)
2019-11-13T18:03:02.7513561Z       at Object.value (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7912:41)
2019-11-13T18:03:02.7514198Z       at /tmp/jsii-kernel-z0oEhd/node_modules/@aws-cdk/core/lib/construct.js:408:50
2019-11-13T18:03:02.7514566Z       at Array.forEach (<anonymous>)
2019-11-13T18:03:02.7515327Z       at ConstructNode.invokeAspects (/tmp/jsii-kernel-z0oEhd/node_modules/@aws-cdk/core/lib/construct.js:408:25)
2019-11-13T18:03:02.7515729Z       at Function.prepare (/tmp/jsii-kernel-z0oEhd/node_modules/@aws-cdk/core/lib/construct.js:82:28)
2019-11-13T18:03:02.7516143Z       at Function.synth (/tmp/jsii-kernel-z0oEhd/node_modules/@aws-cdk/core/lib/construct.js:51:14)
2019-11-13T18:03:02.7516501Z       at App.synth (/tmp/jsii-kernel-z0oEhd/node_modules/@aws-cdk/core/lib/app.js:71:52)
2019-11-13T18:03:02.7516893Z       at Kernel._wrapSandboxCode (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8197:19)
2019-11-13T18:03:02.7517204Z       at /opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7574:25
2019-11-13T18:03:02.7517802Z       at Kernel._ensureSync (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8170:20)
2019-11-13T18:03:02.7518124Z       at Kernel.invoke (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7573:26)
2019-11-13T18:03:02.7518497Z       at KernelHost.processRequest (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7285:28)
2019-11-13T18:03:02.7518827Z       at KernelHost.run (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7225:14)
2019-11-13T18:03:02.7519195Z       at Immediate._onImmediate (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7228:37)
2019-11-13T18:03:02.7519278Z       at processImmediate (internal/timers.js:439:21)
2019-11-13T18:03:02.7519361Z 
2019-11-13T18:03:02.7519431Z The above exception was the direct cause of the following exception:
2019-11-13T18:03:02.7519475Z 
2019-11-13T18:03:02.7519565Z Traceback (most recent call last):
2019-11-13T18:03:02.7519622Z   File "app.py", line 76, in <module>
2019-11-13T18:03:02.7519674Z     run()
2019-11-13T18:03:02.7519766Z   File "app.py", line 50, in run
2019-11-13T18:03:02.7519818Z     app.synth()
2019-11-13T18:03:02.7520153Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 3468, in synth
2019-11-13T18:03:02.7520237Z     return jsii.invoke(self, "synth", [])
2019-11-13T18:03:02.7520569Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 107, in wrapped
2019-11-13T18:03:02.7520651Z     return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
2019-11-13T18:03:02.7520944Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 286, in invoke
2019-11-13T18:03:02.7521075Z     return _callback_till_result(self, response, InvokeResponse)
2019-11-13T18:03:02.7521381Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 173, in _callback_till_result
2019-11-13T18:03:02.7521506Z     response = kernel.sync_complete(response.cbid, str(exc), None, response_type)
2019-11-13T18:03:02.7521806Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 329, in sync_complete
2019-11-13T18:03:02.7522024Z     response_type=response_type
2019-11-13T18:03:02.7522350Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 369, in sync_complete
2019-11-13T18:03:02.7522479Z     resp = self._process.send(_CompleteRequest(complete=request), response_type)
2019-11-13T18:03:02.7522778Z   File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
2019-11-13T18:03:02.7522907Z     raise JSIIError(resp.error) from JavaScriptError(resp.stack)
2019-11-13T18:03:02.7523175Z jsii.errors.JSIIError: 'ConnectorsECSStack' object has no attribute 'ref'
2019-11-13T18:03:02.8126522Z Subprocess exited with error 1
2019-11-13T18:03:06.1566854Z jsii.errors.JavaScriptError: 
2019-11-13T18:03:06.1568518Z   Error: 'ConnectorsECSStack' object has no attribute 'ref'
2019-11-13T18:03:06.1569295Z       at KernelHost.completeCallback (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7250:27)
2019-11-13T18:03:06.1570128Z       at KernelHost.callbackHandler (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:33)
2019-11-13T18:03:06.1570829Z       at Object.value (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7912:41)
2019-11-13T18:03:06.1571525Z       at /tmp/jsii-kernel-DklfFI/node_modules/@aws-cdk/core/lib/construct.js:408:50
2019-11-13T18:03:06.1572201Z       at Array.forEach (<anonymous>)
2019-11-13T18:03:06.1572882Z       at ConstructNode.invokeAspects (/tmp/jsii-kernel-DklfFI/node_modules/@aws-cdk/core/lib/construct.js:408:25)
2019-11-13T18:03:06.1573526Z       at Function.prepare (/tmp/jsii-kernel-DklfFI/node_modules/@aws-cdk/core/lib/construct.js:82:28)
2019-11-13T18:03:06.1574268Z       at Function.synth (/tmp/jsii-kernel-DklfFI/node_modules/@aws-cdk/core/lib/construct.js:51:14)
2019-11-13T18:03:06.1574994Z       at App.synth (/tmp/jsii-kernel-DklfFI/node_modules/@aws-cdk/core/lib/app.js:71:52)
2019-11-13T18:03:06.1575677Z       at Kernel._wrapSandboxCode (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8197:19)
2019-11-13T18:03:06.1576379Z       at /opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7574:25
2019-11-13T18:03:06.1577062Z       at Kernel._ensureSync (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8170:20)
2019-11-13T18:03:06.1577798Z       at Kernel.invoke (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7573:26)
2019-11-13T18:03:06.1578482Z       at KernelHost.processRequest (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7285:28)
2019-11-13T18:03:06.1579219Z       at KernelHost.run (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7225:14)
2019-11-13T18:03:06.1579908Z       at Immediate._onImmediate (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7228:37)
2019-11-13T18:03:06.1580317Z       at processImmediate (internal/timers.js:439:21)
```

**Comment by skinny85** [comment]
@tarunaroraonline I don't think that's the same error...

```
2019-11-13T18:03:06.1568518Z   Error: 'ConnectorsECSStack' object has no attribute 'ref'
```
