### ISSUE TITLE
"TypeError: data_type() got an unexpected keyword argument 'name_mapping'" after upgrading to 1.0.0

### ISSUE THREAD

**Issue by mikemcmaster** [aws/aws-cdk#3293]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

After upgrading to CDK 1.0.0 from 0.39.0, I'm getting this error any time I run stack-related commands:

```
(.env) mike@mike-mbp-2 ~/P/project> npm i -g aws-cdk
/usr/local/bin/cdk -> /usr/local/lib/node_modules/aws-cdk/bin/cdk
+ aws-cdk@1.0.0
updated 7 packages in 8.554s

(.env) mike@mike-mbp-2 ~/P/project> pip install --upgrade -r requirements.txt
Requirement already up-to-date: aws-cdk.cdk in ./.env/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.36.1)
Collecting aws-cdk.aws_ec2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/87/0c/90b7420d14949283fa21ba9e38de10865cb81fbf1e639b3ef9eef933e408/aws_cdk.aws_ec2-1.0.0-py3-none-any.whl (504kB)
    100% |████████████████████████████████| 512kB 4.0MB/s 
<remaining output truncated for brevity>

(.env) mike@mike-mbp-2 ~/P/project> cdk synth
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/Users/mike/Projects/project/.env/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 12, in <module>
    import aws_cdk.cx_api
  File "/Users/mike/Projects/project/.env/lib/python3.7/site-packages/aws_cdk/cx_api/__init__.py", line 12, in <module>
    @jsii.data_type(jsii_type="@aws-cdk/cx-api.ArtifactManifest", jsii_struct_bases=[], name_mapping={'environment': 'environment', 'type': 'type', 'dependencies': 'dependencies', 'metadata': 'metadata', 'properties': 'properties'})
TypeError: data_type() got an unexpected keyword argument 'name_mapping'
Subprocess exited with error 1
```

* **What is the expected behavior (or behavior of feature suggested)?**
`synth` should output CloudFormation as it usually does. Other commands that act on the stack, like `diff`, fail in the same manner. Some commands, such as `cdk doctor`, work as expected.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 1.0.0 (upgraded from 0.39.0, and other versions before that)
  - OS: [OSX Mojave 10.14.5]
  - Language: [Python]

**Comment by DamienPetrilli** [comment]
Same issue. cdk synth doesn't work with python.

`cdk synth
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/Users/damien/Desktop/techlib-cdk/.env/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 12, in <module>
    import aws_cdk.cx_api
  File "/Users/damien/Desktop/techlib-cdk/.env/lib/python3.7/site-packages/aws_cdk/cx_api/__init__.py", line 12, in <module>
    @jsii.data_type(jsii_type="@aws-cdk/cx-api.ArtifactManifest", jsii_struct_bases=[], name_mapping={'environment': 'environment', 'type': 'type', 'dependencies': 'dependencies', 'metadata': 'metadata', 'properties': 'properties'})
TypeError: data_type() got an unexpected keyword argument 'name_mapping'
`

**Comment by NGL321** [comment]
I attempted, but was unable to repro this issue with a very basic Python CDK example (created sample app in 0.39.0, then upgraded to 1.0.0 and ran `cdk synth`).

@garnaat. Any idea about this?

**Comment by mikemcmaster** [comment]
I was poking around some more and this caught my eye:

```
(.env) mike@mike-mbp-2 ~/P/project> pip list aws-cdk.cdk
Package                             Version
----------------------------------- -------
attrs                               19.1.0 
aws-cdk.assets                      1.0.0  
aws-cdk.aws-apigateway              1.0.0  
aws-cdk.aws-applicationautoscaling  1.0.0  
aws-cdk.aws-autoscaling             1.0.0  
aws-cdk.aws-autoscaling-common      1.0.0  
aws-cdk.aws-autoscaling-hooktargets 1.0.0  
aws-cdk.aws-certificatemanager      1.0.0  
aws-cdk.aws-cloudformation          1.0.0  
aws-cdk.aws-cloudfront              1.0.0  
aws-cdk.aws-cloudwatch              1.0.0  
aws-cdk.aws-codebuild               1.0.0  
aws-cdk.aws-codecommit              1.0.0  
aws-cdk.aws-codepipeline            1.0.0  
aws-cdk.aws-ec2                     1.0.0  
aws-cdk.aws-ecr                     1.0.0  
aws-cdk.aws-ecr-assets              1.0.0  
aws-cdk.aws-ecs                     1.0.0  
aws-cdk.aws-ecs-patterns            1.0.0  
aws-cdk.aws-elasticloadbalancing    1.0.0  
aws-cdk.aws-elasticloadbalancingv2  1.0.0  
aws-cdk.aws-events                  1.0.0  
aws-cdk.aws-events-targets          1.0.0  
aws-cdk.aws-iam                     1.0.0  
aws-cdk.aws-kms                     1.0.0  
aws-cdk.aws-lambda                  1.0.0  
aws-cdk.aws-logs                    1.0.0  
aws-cdk.aws-route53                 1.0.0  
aws-cdk.aws-route53-targets         1.0.0  
aws-cdk.aws-s3                      1.0.0  
aws-cdk.aws-s3-assets               1.0.0  
aws-cdk.aws-secretsmanager          1.0.0  
aws-cdk.aws-servicediscovery        1.0.0  
aws-cdk.aws-sns                     1.0.0  
aws-cdk.aws-sns-subscriptions       1.0.0  
aws-cdk.aws-sqs                     1.0.0  
aws-cdk.aws-ssm                     1.0.0  
aws-cdk.aws-stepfunctions           1.0.0  
aws-cdk.cdk                         0.36.1 
aws-cdk.core                        1.0.0  
aws-cdk.custom-resources            1.0.0  
aws-cdk.cx-api                      1.0.0  
aws-cdk.region-info                 1.0.0  
cattrs                              0.9.0  
jsii                                0.13.4 
mypy-extensions                     0.4.1  
pip                                 19.0.3 
publication                         0.0.3  
python-dateutil                     2.8.0  
setuptools                          40.8.0 
six                                 1.12.0 
typing-extensions                   3.7.4 
```

Note the lone `aws-cdk.cdk` package stuck at "0.36.1". I checked it in PyPI, which [noted](https://pypi.org/project/aws-cdk.cdk/) the package is deprecated in favor or `aws-cdk.core`.

I uninstalled it:
```
(.env) mike@mike-mbp-2 ~/P/project> pip uninstall aws-cdk.cdk
Uninstalling aws-cdk.cdk-0.36.1:
  Would remove:
    /Users/mike/Projects/project/.env/lib/python3.7/site-packages/aws_cdk.cdk-0.36.1.dist-info/*
    /Users/mike/Projects/project/.env/lib/python3.7/site-packages/aws_cdk/cdk/_jsii/*
Proceed (y/n)? y
  Successfully uninstalled aws-cdk.cdk-0.36.1
``` 
... and reinstalled `aws-cdk.core`:
```
(.env) mike@mike-mbp-2 ~/P/project> pip install aws-cdk.core
Requirement already satisfied: aws-cdk.core in ./.env/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: aws-cdk.cx-api>=1.0.0,~=1.0 in ./.env/lib/python3.7/site-packages (from aws-cdk.core) (1.0.0)
Collecting jsii~=0.14.0 (from aws-cdk.core)
  Using cached https://files.pythonhosted.org/packages/fc/30/0954b455242b6b9a01f614db21d8a1707d62c7d302420a6c72c93faeb80e/jsii-0.14.0-py3-none-any.whl
Requirement already satisfied: publication>=0.0.3 in ./.env/lib/python3.7/site-packages (from aws-cdk.core) (0.0.3)
Requirement already satisfied: cattrs in ./.env/lib/python3.7/site-packages (from jsii~=0.14.0->aws-cdk.core) (0.9.0)
Requirement already satisfied: python-dateutil in ./.env/lib/python3.7/site-packages (from jsii~=0.14.0->aws-cdk.core) (2.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./.env/lib/python3.7/site-packages (from jsii~=0.14.0->aws-cdk.core) (3.7.4)
Requirement already satisfied: attrs>=18.2 in ./.env/lib/python3.7/site-packages (from jsii~=0.14.0->aws-cdk.core) (19.1.0)
Requirement already satisfied: six>=1.5 in ./.env/lib/python3.7/site-packages (from python-dateutil->jsii~=0.14.0->aws-cdk.core) (1.12.0)
Installing collected packages: jsii
  Found existing installation: jsii 0.13.4
    Uninstalling jsii-0.13.4:
      Successfully uninstalled jsii-0.13.4
Successfully installed jsii-0.14.0
```
After doing this, everything worked again. Note the `jsii` version update, which I suspect was the key to fixing the "TypeError: data_type() got an unexpected keyword argument 'name_mapping'" error. It seems like the `aws-cdk.cdk` -> `aws.cdk.core` package rename was the culprit.

**Comment by eladb** [comment]
Seems like this was resolved. Closing for now.
