### ISSUE TITLE
(backup): BackupVault no longer compatible with kms.CfnReplicaKey

### ISSUE THREAD

**Issue by zessx** [aws/aws-cdk#35899]
### Describe the bug

CDK 2.215.0 introduced new shared interfaces between L1 and L2 resources. Unfortunately the `backup.BackupVault` construct is not yet fully compatible with these interface.

Related code: https://github.com/aws/aws-cdk/pull/35032/files#diff-a31b96329c8b9697f18b560fd50662f96c62739f4513ada812cb6b17f39ecfb8

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.214.0

### Expected Behavior

`backup.BackupVault` should be compatible with `kms.Key`, `kms.CfnKey` and `kms.CfnReplicaKey`.

### Current Behavior

`backup.BackupVault` is not compatible with `kms.CfnReplicaKey`.

### Reproduction Steps

```python
cfn_replica_key = kms.CfnReplicaKey(self, …)

vault = backup.BackupVault(self, "BackupVault",
    encryption_key = cfn_replica_key
)
```

### Additional Information/Context

If I had to create a new vault, I'd probably go for the (L1) `CfnBackupVault` construct, but here we're talking about an existing (L2) vault, which I'm a bit reluctant to "convert" into its L1 version, in regard with its criticality. 

Stack trace:
```txt
jsii.errors.JavaScriptError:
  TypeError: Cannot read properties of undefined (reading 'keyArn')
      at new BackupVault2 (/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/jsii-kernel-ux9aB5]/node_modules/aws-cdk-lib/aws-backup/lib/vault.js:1:7825)
      at new BackupVault2 (/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/jsii-kernel-ux9aB5/node_modules/aws-cdk-lib/core/lib/prop-injectable.js:1:681)
      at Kernel._Kernel_create (/private/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/tmpehohao1c/lib/program.js:549:25)
      at Kernel.create (/private/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/tmpehohao1c/lib/program.js:219:93)
      at KernelHost.processRequest (/private/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/tmpehohao1c/lib/program.js:15482:36)
      at KernelHost.run (/private/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/tmpehohao1c/lib/program.js:15442:22)
      at Immediate._onImmediate (/private/var/folders/mh/fv6nsy211xl_68mfyflgcrh00000gn/T/tmpehohao1c/lib/program.js:15443:45)
      at process.processImmediate (node:internal/timers:491:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[…]/app.py", line 133, in <module>
    BackupStack(app, "Backup", "backup", cross_region_references = True)
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/stacks/backup/stack.py", line 20, in __init__
    replica = BackupReplicaStack(self, "BackupReplica", "backupreplica",
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/stacks/backup/replica.py", line 48, in __init__
    self.vault = backup.BackupVault(self, "ReplicaBackupVault",
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.venv/lib/python3.12/site-packages/aws_cdk/aws_backup/__init__.py", line 4329, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
    
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
               ^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 365, in create
    return self._process.send(request, CreateResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[…]/.venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Cannot read properties of undefined (reading 'keyArn')
```

### AWS CDK Library version (aws-cdk-lib)

2.1031.1

### AWS CDK CLI version

2.221.1

### Node.js Version

v22.11.0

### OS

macOS 15.6.1

### Language

Python

### Language Version

3.12.12

**Comment by pahud** [comment]
Hi,

From my investigation, PR  #35032 introduced the new IKeyRef interface to enable L1/L2 interoperability. `BackupVault.encryptionKey` was updated to accept `IKeyRef` instead of `IKey`. However, `CfnReplicaKey` was not updated to implement IKeyRef, while `CfnKey` was.

I am requesting the team for immediately review.

### Reproduction Code

```ts
import * as cdk from 'aws-cdk-lib';
import * as backup from 'aws-cdk-lib/aws-backup';
import * as kms from 'aws-cdk-lib/aws-kms';
import { Construct } from 'constructs';

export class Issue35899ReproStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // This works - CfnKey implements IKeyRef
    const cfnKey = new kms.CfnKey(this, 'CfnKey', {
      keyPolicy: {
        Statement: [{
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${this.account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });

    new backup.BackupVault(this, 'VaultWithCfnKey', {
      encryptionKey: cfnKey, // ✓ Works
    });

    // This fails - CfnReplicaKey does NOT implement IKeyRef
    const cfnReplicaKey = new kms.CfnReplicaKey(this, 'CfnReplicaKey', {
      primaryKeyArn: 'arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012',
      keyPolicy: {
        Statement: [{
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${this.account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });

    new backup.BackupVault(this, 'VaultWithCfnReplicaKey', {
      encryptionKey: cfnReplicaKey, // ✗ Type error - CfnReplicaKey is not assignable to IKeyRef
    });
  }
}
```

Error Confirmed:
> error TS2741: Property 'keyRef' is missing in type 'CfnReplicaKey' but required in type 'IKeyRef'.


Key Findings:
1. CfnKey works fine with BackupVault (line 23) - it implements IKeyRef
2. CfnReplicaKey fails with BackupVault (line 40) - missing keyRef property


The breaking change started in CDK version 2.215.0

**Comment by mrgrain** [comment]
Hey @zessx I can't reproduce this as a regression. From my investigation, passing a `kms.CfnReplicaKey` to `backup.BackupVault` as `encryptionKey` does not work in `2.214.0.` I've tested this in TS and in Python. As soon as a type checker is involved (e.g. TS or mypy) your example throws. 

Unfortunately without a type checker, the Python code executes without error in `2.214.0`. **However the produced template does not contain the encryption key.** This is arguably even worse than the current behavior.

It makes sense that it is this way. In `2.214.0` and before, we expected `encryptionKey` to be an `kms.IKey`. The code would then go and use the `keyArn` of this object ([as you have found as well](https://github.com/aws/aws-cdk/pull/35032/files#diff-a31b96329c8b9697f18b560fd50662f96c62739f4513ada812cb6b17f39ecfb8L304)).

But [CfnReplicaKey](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kms.CfnReplicaKey.html) doesn't have a `keyArn`. 

---

I agree this should work and we will be looking into this as a future improvement.

For the time being, the easiest work around is probably this:

```py
      cfn_replica_key = kms.CfnReplicaKey(self, "replica", ...)

      vault = backup.BackupVault(self, "BackupVault",
          encryption_key = kms.Key.from_key_arn(self, 'replicaKey', cfn_replica_key.attr_arn)
      )
````

**Comment by zessx** [comment]
I just checked the current CloudFormation template of our stack, and indeed the `AWS::Backup::BackupVault` is missing the `EncryptionKeyArn` property! We unnoticedly used the default `aws/backup` KMS key, not our own.

I'm fine with your workaround, but IIUC I'll have to recreate the whole BackupVault, as I'm changing the KMS key?

**Comment by pahud** [comment]
Hi @zessx 

Unfortunately, yes. As [Type pitfalls](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html) mentioned in the CDK Developer Guide, we recommend PyCharm or MyPy that supports type checking for python to mitigate this unexpected result.


If you run `mypy app.py` with CDK 2.214.0, you will see this error before `cdk synth`

```
app.py:27: error: Argument "encryption_key" to "BackupVault" has
incompatible type "CfnReplicaKey"; expected "IKey | None"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

And that will help you mitigate potential issues like this.

**Comment by zessx** [comment]
I'm not sure if a response is expected from my side or not.

I've re-created the replica vault with success, now using `kms.Key.from_key_arn()` to retrieve my key.
