### ISSUE TITLE
self mutating cdk pipeline fails after updating cdk version from 1.85.0 to 1.92.0

### ISSUE THREAD

**Issue by dhirajkhodade** [aws/aws-cdk#13541]
## :question: General Issue

[Container] 2021/03/11 11:26:36 Phase context status code:  Message: 
[Container] 2021/03/11 11:26:36 Entering phase INSTALL
[Container] 2021/03/11 11:26:36 Phase complete: INSTALL State: SUCCEEDED
[Container] 2021/03/11 11:26:36 Phase context status code:  Message: 
[Container] 2021/03/11 11:26:36 Entering phase PRE_BUILD
[Container] 2021/03/11 11:26:36 Running command npm ci
npm ERR! @aws-cdk/yaml-cfn not accessible from aws-cdk

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-11T11_26_41_322Z-debug.log

[Container] 2021/03/11 11:26:41 Command did not exit successfully npm ci exit status 1
[Container] 2021/03/11 11:26:41 Phase complete: PRE_BUILD State: FAILED
[Container] 2021/03/11 11:26:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm ci. Reason: exit status 1

self-mutating cdk pipeline which was working before is failing with above error in build stage synth action after upgrading cdk version to v1.92.0

### Environment

  - **CDK CLI Version:**  1.92
  - **Module Version:** 
  - **Node.js Version:** 12.16.1
  - **OS:**  Windows 10
  - **Language (Version):**  Typescript

**Comment by Shamail** [comment]
I was using v1.87.1, updated to v1.94.1 and experienced the same issue. I deleted my package-lock file, ran `npm i` and now i'm getting 100+ lines of "Cannot find module or type declarations errors: `node_modules/@aws-cdk/aws-apigateway/lib/access-log.d.ts(1,27): error TS2307: Cannot find module '@aws-cdk/aws-logs' or its corresponding type declarations.`

I also started from scratch in a new project and received the above errors using v1.94.1. 

Once I reverted to `package-lock.json` file that I was using before the update, the build started working again.

**Comment by Shamail** [comment]
@dhirajkhodade My issue was due to the default codebuild image using npm v6.x instead of npm v7.x, which i'm using locally and which produces a `lockfileVersion:2` instead of `lockfileVersion:1` package-lock.json file. So when codebuild pulls the code from my repo, it's getting a package-lock.json that isn't compatible with npm v6.x but it tries to use it anyway without throwing a mismatch error.

Potential solutions:
- Down grade npm locally to v6.x.
- Create/use an image that has npm v7.x and point the environment build image to your image repository like so:
```
         synthAction: SimpleSynthAction.standardNpmSynth({
           ...
           environment: {
             buildImage: codebuild.LinuxBuildImage.fromEcrRepository(...),
           },
         })
```

**Comment by dhirajkhodade** [comment]
Hey @Shamail  Thanks for the details/solution.

I am using default codebuild image and my local npm version  is 7.5.2

```typescript 
synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact: cdkSourceOutput,
        cloudAssemblyArtifact,
        buildCommand: 'npm run build'
      }),
```

Looks like I also have to use custom code build image the way I am using windows image for my legacy .Net builds.

Thanks a ton.

**Comment by peterwoodworth** [comment]
Hey @dhirajkhodade, you need any more help with this? If not, feel free to close the issue
