### ISSUE TITLE
CDK : module 'constructs' has no attribute 'IDependable'

### ISSUE THREAD

**Issue by OK-Cactus** [aws/aws-cdk#17978]
### General Issue

CDK : module 'constructs' has no attribute 'IDependable'

### The Question

On initialising a CDK app (python), while running cdk ls, I'm getting the below errors

cdk ls
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from aws_cdk import core as cdk
  File ".venv/lib/python3.9/site-packages/aws_cdk/__init__.py", line 21457, in <module>
    from . import aws_apigateway
  File "venv/lib/python3.9/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1239, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File ".venv/lib/python3.9/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 187, in <module>
    from ..aws_cloudwatch import (
  File ".venv/lib/python3.9/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 500, in <module>
    from ..aws_iam import Grant as _Grant_a7ae64f8, IGrantable as _IGrantable_71c4f5de
  File ".venv/lib/python3.9/site-packages/aws_cdk/aws_iam/__init__.py", line 476, in <module>
    class AddToPrincipalPolicyResult:
  File ".venv/lib/python3.9/site-packages/aws_cdk/aws_iam/__init__.py", line 480, in AddToPrincipalPolicyResult
    policy_dependable: typing.Optional[constructs.IDependable] = None,
AttributeError: module 'constructs' has no attribute 'IDependable'
Subprocess exited with error 1

Expected output : List the CDK Stack name
These issues started after upgrading cdk version to 2.1.0 

### CDK CLI Version

2.1.0 (build f4f18b1)

### OS

macOs Big Sur 11.6

### Language

Python

### Language Version

Python 3.9.7

**Comment by OK-Cactus** [comment]
Installed constructs using the following command 

`pip install aws_cdk.constructs`

Now getting the following error

```
.venv/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 5470, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)
Subprocess exited with error 1
```

Please suggest steps to correct this

**Comment by OK-Cactus** [comment]
Tried downgrading CDK CLI to 1.128.0, but still same error
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)

**Comment by OK-Cactus** [comment]
Updated CDK version to 2.2.0 and started over again, issue looks fixed

**Comment by aloksinghGIT** [comment]
Even with same Mac machine as above issue, I'm getting the issue even with CDK v2.2.0 while launching cdk synth for the first time
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alok/Documents/DEV/awscdk/app.py", line 4, in <module>
    import aws_cdk as cdk
  File "/Users/alok/Documents/DEV/awscdk/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py", line 21690, in <module>
    from . import aws_acmpca
  File "/Users/alok/Documents/DEV/awscdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_acmpca/__init__.py", line 80, in <module>
    from ._jsii import *
  File "/Users/aloksinr/Documents/DEV/awscdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_acmpca/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/Users/alok/Documents/DEV/awscdk/.venv/lib/python3.10/site-packages/aws_cdk/core/__init__.py", line 5432, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "/Users/alok/Documents/DEV/awscdk/.venv/lib/python3.10/site-packages/aws_cdk/core/__init__.py", line 5470, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)

**Comment by frenayj** [comment]
@aloksinghGIT see https://github.com/aws/aws-cdk/issues/17821

make sure you don't `pip install aws-cdk.aws-*`, that was the issue on my side.

**Comment by chintanghantiwala** [comment]
receiving same error with cdk 2.12.0 in windows. is there any solution for this.

  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\aws_lambda_python\__init__.py", line 213, in <module>
    from ._jsii import *
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\aws_lambda_python\_jsii\__init__.py", line 11, in <module>
    import aws_cdk.aws_ec2._jsii
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\aws_ec2\_jsii\__init__.py", line 11, in <module>
    import aws_cdk.aws_cloudwatch._jsii
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\aws_cloudwatch\_jsii\__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\aws_iam\_jsii\__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\core\__init__.py", line 7146, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "C:\Program Files\Python39\lib\site-packages\aws_cdk\core\__init__.py", line 7197, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: module 'aws_cdk' has no attribute 'cx_api'

**Comment by NaincyKumariKnoldus** [comment]
> Updated CDK version to 2.2.0 and started over again, issue looks fixed

Hey @OK-Cactus I am facing this issue till no. Please do help me. My cdk version is 2.20.0

**Comment by cd17822** [comment]
I was also running into this issue on 2.22.0. I was able to work around it by downgrading to 2.10.0 (no rhyme or reason to this exact version; I just arbitrarily picked a valid version since 2.0.0 and it worked). Still very much hoping this can get resolved soon! 🙏🏼

**Comment by anafaggiano** [comment]
I was using `constructs` `v3.4.7` and it still wasn't working for me. Upgrading to `10.0.0` did it for me. 
I haven't tried in between and haven't investigated when it was fixed. 
Hope this helps someone!
