### ISSUE TITLE
(awslint): namespace import of chalk breaks under esModuleInterop — all lint diagnostics are silently swallowed and builds fail with no output

### ISSUE THREAD

**Issue by laazyj** [aws/aws-cdk#38109]
### Describe the bug

`packages/awslint` is broken on `main`: every lint diagnostic it produces is silently discarded, and when there are error-level findings the build fails at the `cdk-awslint` step with **no output at all**, making the failure undiagnosable.

Root cause: `chalk.red`, `chalk.cyan`, `chalk.bold`, etc. are all `undefined` at runtime, so awslint's result printer never prints and its top-level error handler throws.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

Introduced by #38058 ("chore: prepare repo for TypeScript/JSII 6.0"), which changed `packages/awslint/tsconfig.json` from `"module": "commonjs"` (no `esModuleInterop`) to `"module": "Node20"` **and added `"esModuleInterop": true`**.

### Expected Behavior

`awslint` prints its diagnostics (errors/warnings), and on failure emits a clear message naming the offending rule and scope (e.g. `error: [awslint:docs-public-apis:aws-cdk-lib.pipelines.Step] ...`).

### Current Behavior

- `cd packages/awslint && node bin/awslint.js list` crashes:
  ```
  TypeError: chalk.red is not a function
      at .../packages/awslint/bin/awslint.js:234
  ```
- During a normal build of `packages/aws-cdk-lib`, any awslint **error** makes the build fail with only:
  ```
  Error: .../tools/@aws-cdk/cdk-build-tools/bin/cdk-awslint exited with error code 1
  Build failed.
  ```
  and **zero** diagnostic output. In the results loop the print is gated on `if (color)`, where `color = chalk.red` is `undefined`, so nothing is ever printed — yet `errors++` still runs and sets `process.exitCode = 1`. Warnings are likewise swallowed.

### Reproduction Steps

1. Fresh checkout of `main`, `yarn install`.
2. `cd packages/awslint && npx tsc -b --force`
3. `node bin/awslint.js list` → `TypeError: chalk.red is not a function`.

Root-cause demonstration (mirrors what the compiler emits for `import * as chalk from 'chalk'`):
```js
function importStar(m){var r={};if(m!=null)for(var k in m)if(k!=='default'&&Object.prototype.hasOwnProperty.call(m,k))r[k]=m[k];r.default=m;return r;}
const chalk = importStar(require('chalk'));
typeof require('chalk').red    // 'function'
typeof chalk.red               // 'undefined'   <-- the bug
typeof chalk.default.red       // 'function'    <-- color fns are only on .default
```

### Possible Solution

`bin/awslint.ts` does `import * as chalk from 'chalk'` and accesses `chalk.red`/`chalk.cyan`/`chalk.bold` as namespace members. Under the `esModuleInterop: true` + `module: "Node20"` introduced by #38058 this compiles to `__importStar(require("chalk"))`, and chalk v4 (CJS, default-export function) exposes its color methods only on the wrapper's `.default`, so the namespace members are `undefined`.

Minimal fix: use a default import —
```ts
import chalk from 'chalk';
```
(or upgrade chalk to v5 and use named/default imports). Separately, the top-level `main().catch(e => console.error(chalk.red(e.message)))` should not itself depend on `chalk.red`, so that errors are never silently lost.

### Additional Information/Context

Affects all contributors — any awslint rule violation now fails the build with no actionable message. Discovered when a `docs-public-apis` violation produced a completely silent build failure.

### AWS CDK Library version (aws-cdk-lib)

N/A — internal build tooling (`packages/awslint`), reproduced on `main` @ `35b4d3bb27`.

### AWS CDK CLI version

N/A

### Node.js Version

v24.14.0

### OS

macOS (darwin)

### Language

TypeScript

### Language Version

TypeScript 5.9.3

### Other information

`packages/awslint` declares `chalk: ^4` (installed: 4.1.2). The bug is independent of the chalk patch version; it is the `import * as chalk` + `esModuleInterop` interaction.

**Comment by laazyj** [comment]
I've attached a PR that has a simple fix for this regression

**Comment by pahud** [comment]
Hi @laazyj,

This is a good catch, and a genuinely well-written report — the root-cause analysis is spot on. I went ahead and reproduced it end-to-end against current `main`, and can confirm it's a live regression introduced by #38058.

**Problem at a Glance:**
```
┌──────────────────────────┐      ┌──────────────────────────┐
│  #38058 tsconfig change  │─────▶│  esModuleInterop: true   │
│  module: Node20          │      │  + module: Node20        │
└──────────────────────────┘      └────────────┬─────────────┘
                                               │
                                               ▼
                                  ┌──────────────────────────┐
                                  │  import * as chalk       │
                                  │  → __importStar(require) │
                                  └────────────┬─────────────┘
                                               │
                                               ▼
                                  ┌──────────────────────────┐
                                  │  chalk.red = undefined   │
                                  │  (fns live on .default)  │
                                  └────────────┬─────────────┘
                                               │
                          ┌────────────────────┴────────────────────┐
                          ▼                                          ▼
              ┌──────────────────────┐                  ┌──────────────────────┐
              │  diagnostic printer  │                  │  top-level .catch    │
              │  throws → swallowed  │                  │  ALSO throws on      │
              │  (errors++ silently) │                  │  chalk.red ❌        │
              └──────────────────────┘                  └──────────────────────┘
                          │                                          │
                          └────────────────────┬─────────────────────┘
                                               ▼
                                  ┌──────────────────────────┐
                                  │  Build fails, no output  │
                                  └──────────────────────────┘
```

From my view your diagnosis is exactly right: under the [`esModuleInterop: true`](https://github.com/aws/aws-cdk/blob/main/packages/awslint/tsconfig.json) introduced by #38058, the [`import * as chalk from 'chalk'`](https://github.com/aws/aws-cdk/blob/main/packages/awslint/bin/awslint.ts#L4) namespace import compiles to `__importStar(require("chalk"))`, and chalk v4 (a CJS default-export function) ends up exposing its color methods only on `.default` — so `chalk.red`, `chalk.cyan`, `chalk.bold` are all `undefined`.

Your minimal fix in #38110 (switching to a default import) looks like the correct call. One thing my reproduction surfaced that reinforces your secondary point: the crash actually lands on the top-level handler `console.error(chalk.red(e.message))`, not just the diagnostic printer. So in my opinion hardening that `.catch` so it doesn't itself depend on `chalk` working is worth doing alongside the import fix — otherwise it stays the last place an error can silently disappear.

<details>
<summary><b>How we validated / reproduced this (click to expand)</b></summary>

I confirmed at three levels, all against real `upstream/main` (HEAD `36c84c6d6e`):

**1. Static confirmation — the broken state is live on `main`:**
- #38058 (`d368e215d3 chore: prepare repo for TypeScript/JSII 6.0`) is merged.
- `packages/awslint/tsconfig.json` now has both `"module": "Node20"` and `"esModuleInterop": true`.
- `packages/awslint/bin/awslint.ts:4` is still `import * as chalk from 'chalk'` (fix #38110 not yet merged).
- Declared `chalk: ^4`, installed `4.1.2`.

**2. Mechanism — real chalk 4.1.2 + the exact `__importStar` helper tsc emits:**
```
typeof require('chalk').red    // 'function'
typeof chalk.red               // 'undefined'   ← the bug
typeof chalk.default.red       // 'function'    ← color fns moved here
```

**3. End-to-end — compiled the actual `main` `awslint.ts` with `esModuleInterop: true` and ran it:**
```
// emitted JS:
const chalk = __importStar(require("chalk"));

// node bin/awslint.js list:
TypeError: chalk.red is not a function
    at bin/awslint.js → console.error(chalk.red(e.message));
```
The failure lands on the top-level `.catch` handler, which is exactly why error-level findings produce a completely silent build failure.

**Fix verification** — re-running with the default-import form (`import chalk from 'chalk'` → `chalk_1.default`) restores `typeof chalk.red === 'function'` and prints diagnostics correctly.

</details>

Thanks again for the thorough write-up and the accompanying PR — contributions like this are really valuable. Looking forward to getting #38110 reviewed and merged.

**Comment by pahud** [comment]
Adding the regression window for triage metadata.

**Commit-level (building from `main`):**

| | Commit | Date | awslint tsconfig |
|---|--------|------|------------------|
| **Last working** | `a2263723ef` (#38072) | 2026-06-03 | `module: commonjs`, no `esModuleInterop` ✅ |
| **First broken** | `d368e215d3` (#38058 "prepare repo for TypeScript/JSII 6.0") | 2026-06-03 | `module: Node20` + `esModuleInterop: true` ❌ |
| **Latest `main`** | `36c84c6d6e` | 2026-06-09 | still `import * as chalk` + interop, #38110 **not merged** ❌ |

**Published `awslint` npm package (correction — the published artifact ships the bug too):**

| Published version | Date | Compiled chalk import | Status |
|---|---|---|---|
| `awslint@2.257.0-alpha.0` | 2026-05-21 | `const chalk = require("chalk")` | ✅ last working |
| `awslint@2.258.0-alpha.0` | 2026-06-04 | `const chalk = __importStar(require("chalk"))` | ❌ **first broken** |
| `awslint@2.258.1-alpha.0` | 2026-06-09 | `__importStar(require("chalk"))` | ❌ broken (latest) |

**Impact:**
- **Affected:** contributors building/linting from `main` on/after 2026-06-03, **and** external jsii/construct-library authors who use the published `awslint` package as their linter — anyone on `awslint@2.258.0-alpha.0` or later hits the same silent-failure behavior.
- **Not affected:** regular `aws-cdk-lib` / `aws-cdk` CLI end users — `awslint` is a build/lint tool, not a runtime dependency, so no CDK app's synth or deploy is impacted.

Net: the first broken published version is `awslint@2.258.0-alpha.0`; latest (`2.258.1-alpha.0`) is still broken, and `main` is still broken pending #38110.

**Comment by pahud** [comment]
Regular aws-cdk-lib / aws-cdk CLI end users — awslint isn't a runtime dependency of those, it's a build/lint tool. So no CDK app at runtime or synth is affected. Making this a p1 for now.

**Comment by laazyj** [comment]
@pahud maybe tweak your PR review agent a little to remove ambiguity when responding to possible solutions.

> So in my opinion hardening that .catch so it doesn't itself depend on chalk working is worth doing alongside the import fix — otherwise it stays the last place an error can silently disappear.

Would you like me to update #38110 with this extension? Submit a separate PR? Or is an already authorised contributor going to pick it up and I'd be wasting my time?

Let me know - happy to do the work if it helps
