### ISSUE TITLE
(@aws-cdk/aws-lambda): (missing `logGroup` property in type `FunctionProps` in 2.132.0)

### ISSUE THREAD

**Issue by modosm** [aws/aws-cdk#29439]
### Describe the bug

Missing `logGroup` property in type `FunctionProps` in 2.132.0. This was working in 2.131.0.

 ```
error TS2345: Argument of type '{ runtime: cdk.aws_lambda.Runtime; handler: string; code: cdk.aws_lambda.AssetCode; functionName: string; logGroup: cdk.aws_logs.LogGroup; }' is not assignable to parameter of type 'FunctionProps'.
  Object literal may only specify known properties, and 'logGroup' does not exist in type 'FunctionProps'.

162       logGroup: new logs.LogGroup(this, 'LogGroup', {}),
          ~~~~~~~~
```

### Expected Behavior

`FunctionProps` has `logGroup` property.

### Current Behavior

```
lib/cdk-stack.ts:162:7 - error TS2345: Argument of type '{ runtime: cdk.aws_lambda.Runtime; handler: string; code: cdk.aws_lambda.AssetCode; functionName: string; logGroup: cdk.aws_logs.LogGroup; }' is not assignable to parameter of type 'FunctionProps'.
  Object literal may only specify known properties, and 'logGroup' does not exist in type 'FunctionProps'.

162       logGroup: new logs.LogGroup(this, 'LogGroup', {}),

```

### Reproduction Steps

```typescript
import { LogGroup } from 'aws-cdk-lib/aws-logs';

const myLogGroup = new LogGroup(this, 'MyLogGroupWithLogGroupName', {
  logGroupName: 'customLogGroup',
});

new lambda.Function(this, 'Lambda', {
  code: new lambda.InlineCode('foo'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_18_X,
  logGroup: myLogGroup,
});
```

### CDK CLI Version

1.132.0

### Node.js Version

node/18.19.0

### OS

MacOS Ventura 13.6.4

### Language

TypeScript

**Comment by pahud** [comment]
I think it's still supported:

```ts

export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const myLogGroup = new logs.LogGroup(this, 'MyLogGroupWithLogGroupName', {
      logGroupName: 'customLogGroup',
    });
    
    new lambda.Function(this, 'Lambda', {
      code: new lambda.InlineCode('foo'),
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_18_X,
      logGroup: myLogGroup,
    });

  }
}
```

synth:

```yaml
   Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: foo
      Handler: index.handler
      LoggingConfig:
        LogGroup:
          Ref: MyLogGroupWithLogGroupNameB577EB65
```

Can you verify both your CLI and aws-cdk-lib version are 2.132.0?

% grep aws-cdk-lib package.json 
    "aws-cdk-lib": "2.132.0",
% npx cdk --version
2.132.0 (build 9a51c89)

**Comment by modosm** [comment]
Issue still persists.

 `"aws-cdk-lib": "2.132.0",`

```
pnpm exec cdk --version
2.132.1 (build 9df7dd3)
```

**Comment by pahud** [comment]
>Meanwhile noticed that 2.132.1 was released. Installed it and solved the problem.

Thank you. I am resolving this issue for now.
