### ISSUE TITLE
aws-cdk/Pipeline: Build Stage is Failing at npm ci 

### ISSUE THREAD

**Issue by tuwallace** [aws/aws-cdk#13705]
### Reproduction Steps
Create a CDK Pipeline app with the previous version and verify that builds and deploy successfully
Upgrade the CDK and AWS-CDK node modules to version 1.94.0 and check in the package.json and package.json.lock
Go to the Code Pipeline Console, open the pipeline and check the Build Stage, click details to see the error

### Environment

  - **CDK CLI Version  : 1.94.0
  - **Framework Version:
  - **Node.js Version:v15.9.0
  - **OS               :iOS
  - **Language (Version):typescript 4.2.3 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
CCing @rix0rrr

**Comment by rix0rrr** [comment]
I need more information to debug this, but I have a sense it might be due to NPM 7 on your desktop, NPM 6 on the CodeBuild image.

Try running:

```
npx npm@6 install
```

On your desktop and checking in the `package-lock.json` resulting from that process.

Otherwise, I'm going to need more information on the `package.json` and `package-lock.json`.

**Comment by tuwallace** [comment]
Attached are  my package.json and package-lock.json,   I'm also going try
your suggestion and I think you're on the right track


Taft

**Comment by JFox** [comment]
I had the same issue some minutes ago and it was fixed with this

> Try running:
> 
> ```
> npx npm@6 install
> ```
> 
> On your desktop and checking in the `package-lock.json` resulting from that process.

**Comment by lschierer** [comment]
when will CdkPipeline and SimpleSynthAction.standardNpmSynth support npm v7?

**Comment by tuwallace** [comment]
confirmed ->. using the NPM version 6 resolved my issue, thanks for the
help.

Taft

**Comment by sjohannes** [comment]
I'm also getting this on npm 7. Doesn't happen with pnpm so it could well be an npm 7 bug.

Running `cdk diff` results in

```
Error: Cannot find module '@aws-cdk/yaml-cfn'
Require stack:
- C:\test\node_modules\aws-cdk\lib\serialize.js
- C:\test\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.js
- C:\test\node_modules\aws-cdk\lib\api\bootstrap\index.js
- C:\test\node_modules\aws-cdk\lib\api\index.js
- C:\test\node_modules\aws-cdk\bin\cdk.js
- C:\test\node_modules\aws-cdk\bin\cdk
```

which is strange because `aws-cdk` does specify `@aws-cdk/yaml-cfn` as a dependency.

As a workaround, I've added `@aws-cdk/yaml-cfn` and `aws-sdk` to my project's dependencies, which makes it work with npm 7.

**Comment by tuwallace** [comment]
That is is interesting, I initially tried adding the cited @aws-cdk/yaml-cfn
and I already had the aws-sdk, to resolve the issue, but I started getting
an *archiver not accessible from aws-cdk*, so I switched back to NPM 6
which resolved the issue.

**Comment by hfahlbusch** [comment]
My npm 7 build is working. I had trouble with differences when updating from 6 to 7.  Problem was an out of sync package-lock.json.
You have to use the same version of npm when creating your package-lock.json and when installing with npm ci.

**Solution 1** is to downgrade your local npm version and create the `package-lock.json` with that version.
**Solution 2** is to upgrade your ci system with `npm i -g npm@7` - package lock has to be created with the same version before checking in.

**Comment by rix0rrr** [comment]
Closing this as the particular issue and solution are already addressed in the Pipelines docs.

**Comment by badfun** [comment]
> 
> 
> Closing this as the particular issue and solution are already addressed in the Pipelines docs.

Where would this be? Not finding it in the developer guide, and following the 'How to: Create CDK Pipeline' is failing.

**Comment by lschierer** [comment]
This seems to be fixed for me since CDK updated to include the standard build image 5 instead of the standard build image 4 in v1.101.0

**Comment by badfun** [comment]
I am having that issue following the docs.  Using npm 7.14.0 and cdk 1.106.0

**Comment by lschierer** [comment]
```
    this.TCGPipe = new CdkPipeline(this, 'Pipeline', {                                     
      pipelineName: 'Infrastructure_Pipeline',                                                   
      cloudAssemblyArtifact,                                                                              
      crossAccountKeys: false,                                                                           
      sourceAction: new codepipeline_actions.CodeCommitSourceAction({ 
        actionName: "CodeCommit",                                                     
        branch: "master",                                                                        
        output: sourceArtifact,                                                               
        repository: this.code.repo,                                                         
        trigger: codepipeline_actions.CodeCommitTrigger.EVENTS   
      }),                                                                                         
      synthAction: SimpleSynthAction.standardNpmSynth({  
        sourceArtifact,                             
        cloudAssemblyArtifact,               
        buildCommand: 'npm run build', 
      }),                         
    });                           
```

my package-lock.json shows I'm telling it to use npm 7.14.0 and the cdk 1.106 set of packages.

**Comment by badfun** [comment]
I deleted the stack and re-installed and the issue went away.
