### ISSUE TITLE
aws_ssm: CfnDocument update_method parameter not allowed

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#21116]
### Describe the bug

I tried to do `aws_ssm.CfnDocument(..., update_method="NewVersion", ...)` as mentioned in the docs. https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ssm/CfnDocument.html

### Expected Behavior

It should work.

### Current Behavior

`TypeError: __init__() got an unexpected keyword argument 'update_method'`

### Reproduction Steps

Try to use `update_method`.

### CDK CLI Version

2.21.1 (build a6ee543)

### Node.js Version

v16.15.1

### OS

Alpine 3.16

### Language

Python

### Language Version

3.10.5

**Comment by peterwoodworth** [comment]
I can't reproduce this on Python @rittneje, could you please share full reproduction steps?

**Comment by rittneje** [comment]
@peterwoodworth Turns out `UpdateMethod` was added to to AWS::SSM::Document _very_ recently. https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/173
So that is why it doesn't work on v2.21.1 - the property didn't exist at the time that release was made. I'm guessing you tried to reproduce on the latest CDK version instead.

**Comment by mjvirt** [comment]
I have just run into this issue:
`TypeError: CfnDocument.__init__() got an unexpected keyword argument 'update_method'` when attempting to create a document as follows:

        return ssm.CfnDocument(self, "PublishAMIParameter",
            content=automation_document,
            document_format="YAML",
            document_type="Automation",
            name="PublishAMIParameter",
            update_method="NewVersion"
        )
  
 This is with cdk --version
2.45.0 (build af1fb7c)
 
And same version for library dependency.
Strange thing is, I could deploy it last week with a prior cdk release (not sure what release it was)
