### ISSUE TITLE
(ec2): Unexpected signature change for IVolume.grantAttachVolumeByResourceTag 

### ISSUE THREAD

**Issue by zessx** [aws/aws-cdk#22975]
### Describe the bug

The `IVolume.grantAttachVolumeByResourceTag` signature seems to have changed, as it no longer accept a list of `Construct` in the `contructs` argument.

Still, no trace of any change in [the documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.IVolume.html#grantwbrattachwbrvolumewbrbywbrresourcewbrtaggrantee-constructs-tagkeysuffix) or in the CHANGELOG.

### Expected Behavior

This code is expected to work, like with the version 2.50.0:
```py
volume.grant_attach_volume_by_resource_tag(instance.grant_principal, [instance])
```

### Current Behavior

This code now raises the following error:
```
Traceback (most recent call last):
  File "…/test.py", line 39, in <module>
    DemoStack(app)
  File "…/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "…/test.py", line 36, in __init__
    volume.grant_attach_volume_by_resource_tag(instance.grant_principal, [instance])
  File "…/.venv/lib/python3.10/site-packages/aws_cdk/aws_ec2/__init__.py", line 77309, in grant_attach_volume_by_resource_tag
    constructs: typing.Sequence[constructs.Construct],
AttributeError: 'list' object has no attribute 'Construct'
```

### Reproduction Steps

```py
#!/usr/bin/env python3

from constructs import Construct
from aws_cdk import (
    App,
    Environment,
    Size,
    Stack,
    aws_ec2 as ec2
)

AWS_ACCOUNT = "…"
AWS_REGION = "…"

class DemoStack(Stack):

    def __init__(self, scope: Construct) -> None:
        super().__init__(scope, "DemoStack",
            env = Environment(
                account = AWS_ACCOUNT,
                region = AWS_REGION))

        vpc = ec2.Vpc(self, "Vpc")

        instance = ec2.Instance(self, "Instance",
            instance_type = ec2.InstanceType.of(
                instance_class = ec2.InstanceClass.BURSTABLE3,
                instance_size = ec2.InstanceSize.NANO),
            machine_image = ec2.MachineImage.generic_linux({
                AWS_REGION: "ami-0126a8e63ad208ba5"}),
            vpc = vpc)

        volume = ec2.Volume(self, "Volume",
            availability_zone = vpc.availability_zones[0],
            size = Size.gibibytes(10))

        # Working in 2.50.0, not in 2.51.0
        volume.grant_attach_volume_by_resource_tag(instance.grant_principal, [instance])

app = App()
DemoStack(app)
```

Works with 2.50.0, fails with 2.51.0.

### CDK CLI Version

2.51.0

### Node.js Version

v14.17.6

### OS

macOS 12.3 (21E230)

### Language

Python

### Language Version

Python 3.10.8

**Comment by peterwoodworth** [comment]
Thanks for reporting this, I was able to reproduce this in Python but not in TypeScript, which leads me to believe this might be a JSII regression. We'll look into fixing this soon

**Comment by RomainMuller** [comment]
Confirmed what @peterwoodworth is saying... This is a bug in the `jsii` generated code that stems from the fact the `constructs` parameter shadows the `constructs` library in this particular context, which results in... not what's intended.

**Comment by zessx** [comment]
@RomainMuller As JSII versions are fixed in `package.json`, I'd leave this issue open while the JSII release is not done yet, and used by CDK.

**Comment by peterwoodworth** [comment]
We always close on merge of code, there is going to be some delay between that and the next release on any issue that gets fixed

**Comment by zessx** [comment]
Merged in [JSII 1.72.0](https://github.com/aws/jsii/releases/tag/v1.72.0)

**Comment by zessx** [comment]
And finally deployed with [CDK 2.55.0](https://github.com/aws/aws-cdk/releases/tag/v2.55.0), thanks :)
