### ISSUE TITLE
aws_events: Match.any_of no longer accepts raw strings

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#36902]
### Describe the bug

In v2.216.0, we were able to do `aws_events.Match.any_of("some string")`.

However, upon upgrading to v2.236.0, this started to fail. We had to switch to `aws_events.Match.any_of(aws_events.Match.exact_string("some string"))`.

I did not see this breaking change mentioned anywhere. Was it intentional? If so, please amend the relevant release notes accordingly.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.236.0

### Expected Behavior

It should continue to work, or have been mentioned as a breaking change.

### Current Behavior

It fails.

### Reproduction Steps

See above.

### AWS CDK Library version (aws-cdk-lib)

2.236.0

### AWS CDK CLI version

2.1102.0 (build 8ea0dcb)

### Node.js Version

v24.13.0

### OS

Alpine 3.23.3

### Language

Python

### Language Version

3.14.2

**Comment by pahud** [comment]
Yes I can reproduced using the code

```ts
import * as cdk from 'aws-cdk-lib';
import * as events from 'aws-cdk-lib/aws-events';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'TestStack');

// This worked in v2.216.0 but fails in v2.236.0
const rule = new events.Rule(stack, 'TestRule', {
  eventPattern: {
    source: events.Match.anyOf("aws.s3", "aws.ec2")  // Raw strings - BROKEN
  }
});

app.synth();
```

- **v2.216.0**: ✅ Works — Match.anyOf("aws.s3", "aws.ec2") with raw strings succeeds
- **v2.236.0**: ❌ Fails — TypeError: match.map is not a function

The breaking change was introduced in PR #36602, merged on 2026-01-13, which first appeared in v2.236.0. Any version between v2.216.0 and v2.236.0 where that PR landed would be the first broken
version.

**Comment by pahud** [comment]
@rittneje  Issue fixed. The team will release a patch next Monday. Thank you for the report.
